// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/add_channels.proto

package com.fleetmgr.interfaces;

public interface AddChannelsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.AddChannelsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 channelId = 1;</code>
   */
  java.util.List<java.lang.Long> getChannelIdList();
  /**
   * <code>repeated int64 channelId = 1;</code>
   */
  int getChannelIdCount();
  /**
   * <code>repeated int64 channelId = 1;</code>
   */
  long getChannelId(int index);
}
