// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/add_channels.proto

package com.fleetmgr.interfaces;

/**
 * Protobuf type {@code com.fleetmgr.interfaces.AddChannelsRequest}
 */
public  final class AddChannelsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fleetmgr.interfaces.AddChannelsRequest)
    AddChannelsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddChannelsRequest.newBuilder() to construct.
  private AddChannelsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddChannelsRequest() {
    channelId_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddChannelsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              channelId_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            channelId_.add(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              channelId_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              channelId_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        channelId_ = java.util.Collections.unmodifiableList(channelId_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.AddChannels.internal_static_com_fleetmgr_interfaces_AddChannelsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fleetmgr.interfaces.AddChannels.internal_static_com_fleetmgr_interfaces_AddChannelsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fleetmgr.interfaces.AddChannelsRequest.class, com.fleetmgr.interfaces.AddChannelsRequest.Builder.class);
  }

  public static final int CHANNELID_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Long> channelId_;
  /**
   * <code>repeated int64 channelId = 1;</code>
   */
  public java.util.List<java.lang.Long>
      getChannelIdList() {
    return channelId_;
  }
  /**
   * <code>repeated int64 channelId = 1;</code>
   */
  public int getChannelIdCount() {
    return channelId_.size();
  }
  /**
   * <code>repeated int64 channelId = 1;</code>
   */
  public long getChannelId(int index) {
    return channelId_.get(index);
  }
  private int channelIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getChannelIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(channelIdMemoizedSerializedSize);
    }
    for (int i = 0; i < channelId_.size(); i++) {
      output.writeInt64NoTag(channelId_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < channelId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(channelId_.get(i));
      }
      size += dataSize;
      if (!getChannelIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      channelIdMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fleetmgr.interfaces.AddChannelsRequest)) {
      return super.equals(obj);
    }
    com.fleetmgr.interfaces.AddChannelsRequest other = (com.fleetmgr.interfaces.AddChannelsRequest) obj;

    boolean result = true;
    result = result && getChannelIdList()
        .equals(other.getChannelIdList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChannelIdCount() > 0) {
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.AddChannelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fleetmgr.interfaces.AddChannelsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fleetmgr.interfaces.AddChannelsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fleetmgr.interfaces.AddChannelsRequest)
      com.fleetmgr.interfaces.AddChannelsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fleetmgr.interfaces.AddChannels.internal_static_com_fleetmgr_interfaces_AddChannelsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fleetmgr.interfaces.AddChannels.internal_static_com_fleetmgr_interfaces_AddChannelsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fleetmgr.interfaces.AddChannelsRequest.class, com.fleetmgr.interfaces.AddChannelsRequest.Builder.class);
    }

    // Construct using com.fleetmgr.interfaces.AddChannelsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      channelId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fleetmgr.interfaces.AddChannels.internal_static_com_fleetmgr_interfaces_AddChannelsRequest_descriptor;
    }

    public com.fleetmgr.interfaces.AddChannelsRequest getDefaultInstanceForType() {
      return com.fleetmgr.interfaces.AddChannelsRequest.getDefaultInstance();
    }

    public com.fleetmgr.interfaces.AddChannelsRequest build() {
      com.fleetmgr.interfaces.AddChannelsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.fleetmgr.interfaces.AddChannelsRequest buildPartial() {
      com.fleetmgr.interfaces.AddChannelsRequest result = new com.fleetmgr.interfaces.AddChannelsRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        channelId_ = java.util.Collections.unmodifiableList(channelId_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.channelId_ = channelId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fleetmgr.interfaces.AddChannelsRequest) {
        return mergeFrom((com.fleetmgr.interfaces.AddChannelsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fleetmgr.interfaces.AddChannelsRequest other) {
      if (other == com.fleetmgr.interfaces.AddChannelsRequest.getDefaultInstance()) return this;
      if (!other.channelId_.isEmpty()) {
        if (channelId_.isEmpty()) {
          channelId_ = other.channelId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureChannelIdIsMutable();
          channelId_.addAll(other.channelId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fleetmgr.interfaces.AddChannelsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fleetmgr.interfaces.AddChannelsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Long> channelId_ = java.util.Collections.emptyList();
    private void ensureChannelIdIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        channelId_ = new java.util.ArrayList<java.lang.Long>(channelId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 channelId = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getChannelIdList() {
      return java.util.Collections.unmodifiableList(channelId_);
    }
    /**
     * <code>repeated int64 channelId = 1;</code>
     */
    public int getChannelIdCount() {
      return channelId_.size();
    }
    /**
     * <code>repeated int64 channelId = 1;</code>
     */
    public long getChannelId(int index) {
      return channelId_.get(index);
    }
    /**
     * <code>repeated int64 channelId = 1;</code>
     */
    public Builder setChannelId(
        int index, long value) {
      ensureChannelIdIsMutable();
      channelId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 channelId = 1;</code>
     */
    public Builder addChannelId(long value) {
      ensureChannelIdIsMutable();
      channelId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 channelId = 1;</code>
     */
    public Builder addAllChannelId(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureChannelIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, channelId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 channelId = 1;</code>
     */
    public Builder clearChannelId() {
      channelId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.fleetmgr.interfaces.AddChannelsRequest)
  }

  // @@protoc_insertion_point(class_scope:com.fleetmgr.interfaces.AddChannelsRequest)
  private static final com.fleetmgr.interfaces.AddChannelsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fleetmgr.interfaces.AddChannelsRequest();
  }

  public static com.fleetmgr.interfaces.AddChannelsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddChannelsRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddChannelsRequest>() {
    public AddChannelsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddChannelsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddChannelsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddChannelsRequest> getParserForType() {
    return PARSER;
  }

  public com.fleetmgr.interfaces.AddChannelsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

