// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/add_channels.proto

package com.fleetmgr.interfaces;

public final class AddChannels {
  private AddChannels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_AddChannelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_AddChannelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_AddChannelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_AddChannelsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031common/add_channels.proto\022\027com.fleetmg" +
      "r.interfaces\032\024common/channel.proto\"\'\n\022Ad" +
      "dChannelsRequest\022\021\n\tchannelId\030\001 \003(\003\"H\n\023A" +
      "ddChannelsResponse\0221\n\007channel\030\001 \003(\0132 .co" +
      "m.fleetmgr.interfaces.ChannelB\002P\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fleetmgr.interfaces.ChannelOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fleetmgr_interfaces_AddChannelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fleetmgr_interfaces_AddChannelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_AddChannelsRequest_descriptor,
        new java.lang.String[] { "ChannelId", });
    internal_static_com_fleetmgr_interfaces_AddChannelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fleetmgr_interfaces_AddChannelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_AddChannelsResponse_descriptor,
        new java.lang.String[] { "Channel", });
    com.fleetmgr.interfaces.ChannelOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
