// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/attach_channels.proto

package com.fleetmgr.interfaces;

/**
 * Protobuf type {@code com.fleetmgr.interfaces.AttachChannelsRequest}
 */
public  final class AttachChannelsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fleetmgr.interfaces.AttachChannelsRequest)
    AttachChannelsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AttachChannelsRequest.newBuilder() to construct.
  private AttachChannelsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AttachChannelsRequest() {
    channels_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AttachChannelsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              channels_ = new java.util.ArrayList<com.fleetmgr.interfaces.Channel>();
              mutable_bitField0_ |= 0x00000001;
            }
            channels_.add(
                input.readMessage(com.fleetmgr.interfaces.Channel.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        channels_ = java.util.Collections.unmodifiableList(channels_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.AttachChannels.internal_static_com_fleetmgr_interfaces_AttachChannelsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fleetmgr.interfaces.AttachChannels.internal_static_com_fleetmgr_interfaces_AttachChannelsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fleetmgr.interfaces.AttachChannelsRequest.class, com.fleetmgr.interfaces.AttachChannelsRequest.Builder.class);
  }

  public static final int CHANNELS_FIELD_NUMBER = 1;
  private java.util.List<com.fleetmgr.interfaces.Channel> channels_;
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  public java.util.List<com.fleetmgr.interfaces.Channel> getChannelsList() {
    return channels_;
  }
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  public java.util.List<? extends com.fleetmgr.interfaces.ChannelOrBuilder> 
      getChannelsOrBuilderList() {
    return channels_;
  }
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  public int getChannelsCount() {
    return channels_.size();
  }
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  public com.fleetmgr.interfaces.Channel getChannels(int index) {
    return channels_.get(index);
  }
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  public com.fleetmgr.interfaces.ChannelOrBuilder getChannelsOrBuilder(
      int index) {
    return channels_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < channels_.size(); i++) {
      output.writeMessage(1, channels_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < channels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, channels_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fleetmgr.interfaces.AttachChannelsRequest)) {
      return super.equals(obj);
    }
    com.fleetmgr.interfaces.AttachChannelsRequest other = (com.fleetmgr.interfaces.AttachChannelsRequest) obj;

    boolean result = true;
    result = result && getChannelsList()
        .equals(other.getChannelsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChannelsCount() > 0) {
      hash = (37 * hash) + CHANNELS_FIELD_NUMBER;
      hash = (53 * hash) + getChannelsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.AttachChannelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fleetmgr.interfaces.AttachChannelsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fleetmgr.interfaces.AttachChannelsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fleetmgr.interfaces.AttachChannelsRequest)
      com.fleetmgr.interfaces.AttachChannelsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fleetmgr.interfaces.AttachChannels.internal_static_com_fleetmgr_interfaces_AttachChannelsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fleetmgr.interfaces.AttachChannels.internal_static_com_fleetmgr_interfaces_AttachChannelsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fleetmgr.interfaces.AttachChannelsRequest.class, com.fleetmgr.interfaces.AttachChannelsRequest.Builder.class);
    }

    // Construct using com.fleetmgr.interfaces.AttachChannelsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChannelsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (channelsBuilder_ == null) {
        channels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        channelsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fleetmgr.interfaces.AttachChannels.internal_static_com_fleetmgr_interfaces_AttachChannelsRequest_descriptor;
    }

    public com.fleetmgr.interfaces.AttachChannelsRequest getDefaultInstanceForType() {
      return com.fleetmgr.interfaces.AttachChannelsRequest.getDefaultInstance();
    }

    public com.fleetmgr.interfaces.AttachChannelsRequest build() {
      com.fleetmgr.interfaces.AttachChannelsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.fleetmgr.interfaces.AttachChannelsRequest buildPartial() {
      com.fleetmgr.interfaces.AttachChannelsRequest result = new com.fleetmgr.interfaces.AttachChannelsRequest(this);
      int from_bitField0_ = bitField0_;
      if (channelsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          channels_ = java.util.Collections.unmodifiableList(channels_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.channels_ = channels_;
      } else {
        result.channels_ = channelsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fleetmgr.interfaces.AttachChannelsRequest) {
        return mergeFrom((com.fleetmgr.interfaces.AttachChannelsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fleetmgr.interfaces.AttachChannelsRequest other) {
      if (other == com.fleetmgr.interfaces.AttachChannelsRequest.getDefaultInstance()) return this;
      if (channelsBuilder_ == null) {
        if (!other.channels_.isEmpty()) {
          if (channels_.isEmpty()) {
            channels_ = other.channels_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChannelsIsMutable();
            channels_.addAll(other.channels_);
          }
          onChanged();
        }
      } else {
        if (!other.channels_.isEmpty()) {
          if (channelsBuilder_.isEmpty()) {
            channelsBuilder_.dispose();
            channelsBuilder_ = null;
            channels_ = other.channels_;
            bitField0_ = (bitField0_ & ~0x00000001);
            channelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChannelsFieldBuilder() : null;
          } else {
            channelsBuilder_.addAllMessages(other.channels_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fleetmgr.interfaces.AttachChannelsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fleetmgr.interfaces.AttachChannelsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.fleetmgr.interfaces.Channel> channels_ =
      java.util.Collections.emptyList();
    private void ensureChannelsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        channels_ = new java.util.ArrayList<com.fleetmgr.interfaces.Channel>(channels_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fleetmgr.interfaces.Channel, com.fleetmgr.interfaces.Channel.Builder, com.fleetmgr.interfaces.ChannelOrBuilder> channelsBuilder_;

    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public java.util.List<com.fleetmgr.interfaces.Channel> getChannelsList() {
      if (channelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(channels_);
      } else {
        return channelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public int getChannelsCount() {
      if (channelsBuilder_ == null) {
        return channels_.size();
      } else {
        return channelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public com.fleetmgr.interfaces.Channel getChannels(int index) {
      if (channelsBuilder_ == null) {
        return channels_.get(index);
      } else {
        return channelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder setChannels(
        int index, com.fleetmgr.interfaces.Channel value) {
      if (channelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelsIsMutable();
        channels_.set(index, value);
        onChanged();
      } else {
        channelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder setChannels(
        int index, com.fleetmgr.interfaces.Channel.Builder builderForValue) {
      if (channelsBuilder_ == null) {
        ensureChannelsIsMutable();
        channels_.set(index, builderForValue.build());
        onChanged();
      } else {
        channelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder addChannels(com.fleetmgr.interfaces.Channel value) {
      if (channelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelsIsMutable();
        channels_.add(value);
        onChanged();
      } else {
        channelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder addChannels(
        int index, com.fleetmgr.interfaces.Channel value) {
      if (channelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelsIsMutable();
        channels_.add(index, value);
        onChanged();
      } else {
        channelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder addChannels(
        com.fleetmgr.interfaces.Channel.Builder builderForValue) {
      if (channelsBuilder_ == null) {
        ensureChannelsIsMutable();
        channels_.add(builderForValue.build());
        onChanged();
      } else {
        channelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder addChannels(
        int index, com.fleetmgr.interfaces.Channel.Builder builderForValue) {
      if (channelsBuilder_ == null) {
        ensureChannelsIsMutable();
        channels_.add(index, builderForValue.build());
        onChanged();
      } else {
        channelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder addAllChannels(
        java.lang.Iterable<? extends com.fleetmgr.interfaces.Channel> values) {
      if (channelsBuilder_ == null) {
        ensureChannelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, channels_);
        onChanged();
      } else {
        channelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder clearChannels() {
      if (channelsBuilder_ == null) {
        channels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        channelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public Builder removeChannels(int index) {
      if (channelsBuilder_ == null) {
        ensureChannelsIsMutable();
        channels_.remove(index);
        onChanged();
      } else {
        channelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public com.fleetmgr.interfaces.Channel.Builder getChannelsBuilder(
        int index) {
      return getChannelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public com.fleetmgr.interfaces.ChannelOrBuilder getChannelsOrBuilder(
        int index) {
      if (channelsBuilder_ == null) {
        return channels_.get(index);  } else {
        return channelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public java.util.List<? extends com.fleetmgr.interfaces.ChannelOrBuilder> 
         getChannelsOrBuilderList() {
      if (channelsBuilder_ != null) {
        return channelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(channels_);
      }
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public com.fleetmgr.interfaces.Channel.Builder addChannelsBuilder() {
      return getChannelsFieldBuilder().addBuilder(
          com.fleetmgr.interfaces.Channel.getDefaultInstance());
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public com.fleetmgr.interfaces.Channel.Builder addChannelsBuilder(
        int index) {
      return getChannelsFieldBuilder().addBuilder(
          index, com.fleetmgr.interfaces.Channel.getDefaultInstance());
    }
    /**
     * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
     */
    public java.util.List<com.fleetmgr.interfaces.Channel.Builder> 
         getChannelsBuilderList() {
      return getChannelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fleetmgr.interfaces.Channel, com.fleetmgr.interfaces.Channel.Builder, com.fleetmgr.interfaces.ChannelOrBuilder> 
        getChannelsFieldBuilder() {
      if (channelsBuilder_ == null) {
        channelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.fleetmgr.interfaces.Channel, com.fleetmgr.interfaces.Channel.Builder, com.fleetmgr.interfaces.ChannelOrBuilder>(
                channels_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        channels_ = null;
      }
      return channelsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.fleetmgr.interfaces.AttachChannelsRequest)
  }

  // @@protoc_insertion_point(class_scope:com.fleetmgr.interfaces.AttachChannelsRequest)
  private static final com.fleetmgr.interfaces.AttachChannelsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fleetmgr.interfaces.AttachChannelsRequest();
  }

  public static com.fleetmgr.interfaces.AttachChannelsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttachChannelsRequest>
      PARSER = new com.google.protobuf.AbstractParser<AttachChannelsRequest>() {
    public AttachChannelsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AttachChannelsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AttachChannelsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttachChannelsRequest> getParserForType() {
    return PARSER;
  }

  public com.fleetmgr.interfaces.AttachChannelsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

