// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/attach_channels.proto

package com.fleetmgr.interfaces;

public interface AttachChannelsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.AttachChannelsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  java.util.List<com.fleetmgr.interfaces.Channel> 
      getChannelsList();
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  com.fleetmgr.interfaces.Channel getChannels(int index);
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  int getChannelsCount();
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  java.util.List<? extends com.fleetmgr.interfaces.ChannelOrBuilder> 
      getChannelsOrBuilderList();
  /**
   * <code>repeated .com.fleetmgr.interfaces.Channel channels = 1;</code>
   */
  com.fleetmgr.interfaces.ChannelOrBuilder getChannelsOrBuilder(
      int index);
}
