// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/attach.proto

package com.fleetmgr.interfaces;

public final class Attach {
  private Attach() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_AttachResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_AttachResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021core/attach.proto\022\027com.fleetmgr.interf" +
      "aces\"9\n\016AttachResponse\022\014\n\004host\030\001 \001(\t\022\014\n\004" +
      "port\030\002 \001(\005\022\013\n\003key\030\003 \001(\tB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fleetmgr_interfaces_AttachResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fleetmgr_interfaces_AttachResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_AttachResponse_descriptor,
        new java.lang.String[] { "Host", "Port", "Key", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
