// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/channel.proto

package com.fleetmgr.interfaces;

public interface ChannelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.Channel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string ip = 2;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();

  /**
   * <code>string routeKey = 4;</code>
   */
  java.lang.String getRouteKey();
  /**
   * <code>string routeKey = 4;</code>
   */
  com.google.protobuf.ByteString
      getRouteKeyBytes();
}
