// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/channel_validation.proto

package com.fleetmgr.interfaces;

public final class ChannelValidation {
  private ChannelValidation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_ValidateChannelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_ValidateChannelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_ValidateChannelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_ValidateChannelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037common/channel_validation.proto\022\027com.f" +
      "leetmgr.interfaces\"%\n\026ValidateChannelReq" +
      "uest\022\013\n\003key\030\001 \001(\t\"[\n\027ValidateChannelResp" +
      "onse\022/\n\006result\030\001 \001(\0162\037.com.fleetmgr.inte" +
      "rfaces.Result\022\017\n\007message\030\002 \001(\t*I\n\006Result" +
      "\022\r\n\tUNDEFINED\020\000\022\027\n\023VALIDATION_ACCEPTED\020\001" +
      "\022\027\n\023VALIDATION_REJECTED\020\002B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fleetmgr_interfaces_ValidateChannelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fleetmgr_interfaces_ValidateChannelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_ValidateChannelRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_com_fleetmgr_interfaces_ValidateChannelResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fleetmgr_interfaces_ValidateChannelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_ValidateChannelResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
