// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/attach_channels.proto

package com.fleetmgr.interfaces;

public interface ChannelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.ChannelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint64 attachedChannels = 1;</code>
   */
  java.util.List<java.lang.Long> getAttachedChannelsList();
  /**
   * <code>repeated uint64 attachedChannels = 1;</code>
   */
  int getAttachedChannelsCount();
  /**
   * <code>repeated uint64 attachedChannels = 1;</code>
   */
  long getAttachedChannels(int index);
}
