// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/connection_state.proto

package com.fleetmgr.interfaces;

public final class ConnectionStateOuterClass {
  private ConnectionStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035common/connection_state.proto\022\027com.fle" +
      "etmgr.interfaces*s\n\017ConnectionState\022\036\n\032U" +
      "NDEFINED_CONNECTION_STATE\020\000\022\016\n\nCONNECTIN" +
      "G\020\001\022\r\n\tCONNECTED\020\002\022\017\n\013UNREACHABLE\020\003\022\020\n\014D" +
      "ISCONNECTED\020\004B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
