// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/connection_state.proto

package com.fleetmgr.interfaces;

/**
 * Protobuf enum {@code com.fleetmgr.interfaces.ConnectionState}
 */
public enum ConnectionState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNDEFINED_CONNECTION_STATE = 0;</code>
   */
  UNDEFINED_CONNECTION_STATE(0),
  /**
   * <code>CONNECTING = 1;</code>
   */
  CONNECTING(1),
  /**
   * <code>CONNECTED = 2;</code>
   */
  CONNECTED(2),
  /**
   * <code>UNREACHABLE = 3;</code>
   */
  UNREACHABLE(3),
  /**
   * <code>DISCONNECTED = 4;</code>
   */
  DISCONNECTED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNDEFINED_CONNECTION_STATE = 0;</code>
   */
  public static final int UNDEFINED_CONNECTION_STATE_VALUE = 0;
  /**
   * <code>CONNECTING = 1;</code>
   */
  public static final int CONNECTING_VALUE = 1;
  /**
   * <code>CONNECTED = 2;</code>
   */
  public static final int CONNECTED_VALUE = 2;
  /**
   * <code>UNREACHABLE = 3;</code>
   */
  public static final int UNREACHABLE_VALUE = 3;
  /**
   * <code>DISCONNECTED = 4;</code>
   */
  public static final int DISCONNECTED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConnectionState valueOf(int value) {
    return forNumber(value);
  }

  public static ConnectionState forNumber(int value) {
    switch (value) {
      case 0: return UNDEFINED_CONNECTION_STATE;
      case 1: return CONNECTING;
      case 2: return CONNECTED;
      case 3: return UNREACHABLE;
      case 4: return DISCONNECTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConnectionState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConnectionState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConnectionState>() {
          public ConnectionState findValueByNumber(int number) {
            return ConnectionState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.ConnectionStateOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ConnectionState[] VALUES = values();

  public static ConnectionState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ConnectionState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.fleetmgr.interfaces.ConnectionState)
}

