// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/list_devices.proto

package com.fleetmgr.interfaces;

public interface DeviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.Device)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.com.fleetmgr.interfaces.ConnectionState connectionState = 3;</code>
   */
  int getConnectionStateValue();
  /**
   * <code>.com.fleetmgr.interfaces.ConnectionState connectionState = 3;</code>
   */
  com.fleetmgr.interfaces.ConnectionState getConnectionState();

  /**
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
