// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/handover_data.proto

package com.fleetmgr.interfaces;

public interface HandoverDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.HandoverData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string handoverData = 1;</code>
   */
  java.lang.String getHandoverData();
  /**
   * <code>string handoverData = 1;</code>
   */
  com.google.protobuf.ByteString
      getHandoverDataBytes();
}
