// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/list_devices.proto

package com.fleetmgr.interfaces;

public final class ListDevices {
  private ListDevices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_ListDevicesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_ListDevicesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027core/list_devices.proto\022\027com.fleetmgr." +
      "interfaces\032\035common/connection_state.prot" +
      "o\"s\n\006Device\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022A\n" +
      "\017connectionState\030\003 \001(\0162(.com.fleetmgr.in" +
      "terfaces.ConnectionState\022\014\n\004type\030\004 \001(\t\"G" +
      "\n\023ListDevicesResponse\0220\n\007devices\030\001 \003(\0132\037" +
      ".com.fleetmgr.interfaces.DeviceB\002P\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fleetmgr.interfaces.ConnectionStateOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fleetmgr_interfaces_Device_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fleetmgr_interfaces_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_Device_descriptor,
        new java.lang.String[] { "Id", "Name", "ConnectionState", "Type", });
    internal_static_com_fleetmgr_interfaces_ListDevicesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fleetmgr_interfaces_ListDevicesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_ListDevicesResponse_descriptor,
        new java.lang.String[] { "Devices", });
    com.fleetmgr.interfaces.ConnectionStateOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
