// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/location.proto

package com.fleetmgr.interfaces;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitude = 1;</code>
   */
  double getLatitude();

  /**
   * <code>double longitude = 2;</code>
   */
  double getLongitude();

  /**
   * <code>double altitude = 3;</code>
   */
  double getAltitude();
}
