// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/operate.proto

package com.fleetmgr.interfaces;

public final class Operate {
  private Operate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_OperateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_OperateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_OperateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_OperateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022core/operate.proto\022\027com.fleetmgr.inter" +
      "faces\032\021common/role.proto\"+\n\016OperateReque" +
      "st\022\031\n\021requestedDeviceId\030\001 \001(\004\"g\n\017Operate" +
      "Response\022\014\n\004host\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\013\n\003" +
      "key\030\003 \001(\t\022+\n\004role\030\004 \001(\0162\035.com.fleetmgr.i" +
      "nterfaces.RoleB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fleetmgr.interfaces.RoleOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_fleetmgr_interfaces_OperateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fleetmgr_interfaces_OperateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_OperateRequest_descriptor,
        new java.lang.String[] { "RequestedDeviceId", });
    internal_static_com_fleetmgr_interfaces_OperateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fleetmgr_interfaces_OperateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_OperateResponse_descriptor,
        new java.lang.String[] { "Host", "Port", "Key", "Role", });
    com.fleetmgr.interfaces.RoleOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
