// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/operate.proto

package com.fleetmgr.interfaces;

public interface OperateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.OperateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 requestedDeviceId = 1;</code>
   */
  long getRequestedDeviceId();
}
