// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/operate.proto

package com.fleetmgr.interfaces;

public interface OperateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.OperateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host = 1;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>string key = 3;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.com.fleetmgr.interfaces.Role role = 4;</code>
   */
  int getRoleValue();
  /**
   * <code>.com.fleetmgr.interfaces.Role role = 4;</code>
   */
  com.fleetmgr.interfaces.Role getRole();
}
