// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/role.proto

package com.fleetmgr.interfaces;

/**
 * Protobuf enum {@code com.fleetmgr.interfaces.Role}
 */
public enum Role
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNDEFINED_ROLE = 0;</code>
   */
  UNDEFINED_ROLE(0),
  /**
   * <code>DEVICE = 1;</code>
   */
  DEVICE(1),
  /**
   * <code>LEADER = 2;</code>
   */
  LEADER(2),
  /**
   * <code>PILOT = 3;</code>
   */
  PILOT(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNDEFINED_ROLE = 0;</code>
   */
  public static final int UNDEFINED_ROLE_VALUE = 0;
  /**
   * <code>DEVICE = 1;</code>
   */
  public static final int DEVICE_VALUE = 1;
  /**
   * <code>LEADER = 2;</code>
   */
  public static final int LEADER_VALUE = 2;
  /**
   * <code>PILOT = 3;</code>
   */
  public static final int PILOT_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Role valueOf(int value) {
    return forNumber(value);
  }

  public static Role forNumber(int value) {
    switch (value) {
      case 0: return UNDEFINED_ROLE;
      case 1: return DEVICE;
      case 2: return LEADER;
      case 3: return PILOT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Role>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Role> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Role>() {
          public Role findValueByNumber(int number) {
            return Role.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.RoleOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final Role[] VALUES = values();

  public static Role valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Role(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.fleetmgr.interfaces.Role)
}

