// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/channel_validation.proto

package com.fleetmgr.interfaces;

public interface ValidateChannelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.ValidateChannelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
