// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/channel_validation.proto

package com.fleetmgr.interfaces;

public interface ValidateChannelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.ValidateChannelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.fleetmgr.interfaces.Result result = 1;</code>
   */
  int getResultValue();
  /**
   * <code>.com.fleetmgr.interfaces.Result result = 1;</code>
   */
  com.fleetmgr.interfaces.Result getResult();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
