// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/facade_service.proto

package com.fleetmgr.interfaces.facade.control;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.facade.control.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  int getCommandValue();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  com.fleetmgr.interfaces.facade.control.Command getCommand();

  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  int getResponseValue();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  com.fleetmgr.interfaces.facade.control.Response getResponse();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
   */
  boolean hasAttach();
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
   */
  com.fleetmgr.interfaces.facade.control.SetupRequest getAttach();
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
   */
  com.fleetmgr.interfaces.facade.control.SetupRequestOrBuilder getAttachOrBuilder();

  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
   */
  boolean hasRequestChannels();
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
   */
  com.fleetmgr.interfaces.AddChannelsRequest getRequestChannels();
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
   */
  com.fleetmgr.interfaces.AddChannelsRequestOrBuilder getRequestChannelsOrBuilder();

  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
   */
  boolean hasAttachChannels();
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
   */
  com.fleetmgr.interfaces.ChannelsResponse getAttachChannels();
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
   */
  com.fleetmgr.interfaces.ChannelsResponseOrBuilder getAttachChannelsOrBuilder();

  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
   */
  boolean hasHandoverData();
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
   */
  com.fleetmgr.interfaces.HandoverData getHandoverData();
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
   */
  com.fleetmgr.interfaces.HandoverDataOrBuilder getHandoverDataOrBuilder();

  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
   */
  boolean hasHeartbeat();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
   */
  com.fleetmgr.interfaces.facade.control.HeartbeatResponse getHeartbeat();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
   */
  com.fleetmgr.interfaces.facade.control.HeartbeatResponseOrBuilder getHeartbeatOrBuilder();
}
