// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/facade_service.proto

package com.fleetmgr.interfaces.facade.control;

/**
 * Protobuf type {@code com.fleetmgr.interfaces.facade.control.ClientMessage}
 */
public  final class ClientMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fleetmgr.interfaces.facade.control.ClientMessage)
    ClientMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientMessage.newBuilder() to construct.
  private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientMessage() {
    command_ = 0;
    response_ = 0;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            response_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 402: {
            com.fleetmgr.interfaces.facade.control.SetupRequest.Builder subBuilder = null;
            if (attach_ != null) {
              subBuilder = attach_.toBuilder();
            }
            attach_ = input.readMessage(com.fleetmgr.interfaces.facade.control.SetupRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(attach_);
              attach_ = subBuilder.buildPartial();
            }

            break;
          }
          case 410: {
            com.fleetmgr.interfaces.AddChannelsRequest.Builder subBuilder = null;
            if (requestChannels_ != null) {
              subBuilder = requestChannels_.toBuilder();
            }
            requestChannels_ = input.readMessage(com.fleetmgr.interfaces.AddChannelsRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestChannels_);
              requestChannels_ = subBuilder.buildPartial();
            }

            break;
          }
          case 802: {
            com.fleetmgr.interfaces.ChannelsResponse.Builder subBuilder = null;
            if (attachChannels_ != null) {
              subBuilder = attachChannels_.toBuilder();
            }
            attachChannels_ = input.readMessage(com.fleetmgr.interfaces.ChannelsResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(attachChannels_);
              attachChannels_ = subBuilder.buildPartial();
            }

            break;
          }
          case 810: {
            com.fleetmgr.interfaces.HandoverData.Builder subBuilder = null;
            if (handoverData_ != null) {
              subBuilder = handoverData_.toBuilder();
            }
            handoverData_ = input.readMessage(com.fleetmgr.interfaces.HandoverData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(handoverData_);
              handoverData_ = subBuilder.buildPartial();
            }

            break;
          }
          case 818: {
            com.fleetmgr.interfaces.facade.control.HeartbeatResponse.Builder subBuilder = null;
            if (heartbeat_ != null) {
              subBuilder = heartbeat_.toBuilder();
            }
            heartbeat_ = input.readMessage(com.fleetmgr.interfaces.facade.control.HeartbeatResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(heartbeat_);
              heartbeat_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fleetmgr.interfaces.facade.control.ClientMessage.class, com.fleetmgr.interfaces.facade.control.ClientMessage.Builder.class);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  private int command_;
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  public com.fleetmgr.interfaces.facade.control.Command getCommand() {
    com.fleetmgr.interfaces.facade.control.Command result = com.fleetmgr.interfaces.facade.control.Command.valueOf(command_);
    return result == null ? com.fleetmgr.interfaces.facade.control.Command.UNRECOGNIZED : result;
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  private int response_;
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  public int getResponseValue() {
    return response_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  public com.fleetmgr.interfaces.facade.control.Response getResponse() {
    com.fleetmgr.interfaces.facade.control.Response result = com.fleetmgr.interfaces.facade.control.Response.valueOf(response_);
    return result == null ? com.fleetmgr.interfaces.facade.control.Response.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTACH_FIELD_NUMBER = 50;
  private com.fleetmgr.interfaces.facade.control.SetupRequest attach_;
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
   */
  public boolean hasAttach() {
    return attach_ != null;
  }
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
   */
  public com.fleetmgr.interfaces.facade.control.SetupRequest getAttach() {
    return attach_ == null ? com.fleetmgr.interfaces.facade.control.SetupRequest.getDefaultInstance() : attach_;
  }
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
   */
  public com.fleetmgr.interfaces.facade.control.SetupRequestOrBuilder getAttachOrBuilder() {
    return getAttach();
  }

  public static final int REQUESTCHANNELS_FIELD_NUMBER = 51;
  private com.fleetmgr.interfaces.AddChannelsRequest requestChannels_;
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
   */
  public boolean hasRequestChannels() {
    return requestChannels_ != null;
  }
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
   */
  public com.fleetmgr.interfaces.AddChannelsRequest getRequestChannels() {
    return requestChannels_ == null ? com.fleetmgr.interfaces.AddChannelsRequest.getDefaultInstance() : requestChannels_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
   */
  public com.fleetmgr.interfaces.AddChannelsRequestOrBuilder getRequestChannelsOrBuilder() {
    return getRequestChannels();
  }

  public static final int ATTACHCHANNELS_FIELD_NUMBER = 100;
  private com.fleetmgr.interfaces.ChannelsResponse attachChannels_;
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
   */
  public boolean hasAttachChannels() {
    return attachChannels_ != null;
  }
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
   */
  public com.fleetmgr.interfaces.ChannelsResponse getAttachChannels() {
    return attachChannels_ == null ? com.fleetmgr.interfaces.ChannelsResponse.getDefaultInstance() : attachChannels_;
  }
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
   */
  public com.fleetmgr.interfaces.ChannelsResponseOrBuilder getAttachChannelsOrBuilder() {
    return getAttachChannels();
  }

  public static final int HANDOVERDATA_FIELD_NUMBER = 101;
  private com.fleetmgr.interfaces.HandoverData handoverData_;
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
   */
  public boolean hasHandoverData() {
    return handoverData_ != null;
  }
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
   */
  public com.fleetmgr.interfaces.HandoverData getHandoverData() {
    return handoverData_ == null ? com.fleetmgr.interfaces.HandoverData.getDefaultInstance() : handoverData_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
   */
  public com.fleetmgr.interfaces.HandoverDataOrBuilder getHandoverDataOrBuilder() {
    return getHandoverData();
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 102;
  private com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat_;
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
   */
  public boolean hasHeartbeat() {
    return heartbeat_ != null;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
   */
  public com.fleetmgr.interfaces.facade.control.HeartbeatResponse getHeartbeat() {
    return heartbeat_ == null ? com.fleetmgr.interfaces.facade.control.HeartbeatResponse.getDefaultInstance() : heartbeat_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
   */
  public com.fleetmgr.interfaces.facade.control.HeartbeatResponseOrBuilder getHeartbeatOrBuilder() {
    return getHeartbeat();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (command_ != com.fleetmgr.interfaces.facade.control.Command.UNDEFINED_CMD.getNumber()) {
      output.writeEnum(1, command_);
    }
    if (response_ != com.fleetmgr.interfaces.facade.control.Response.UNDEFINED_RSP.getNumber()) {
      output.writeEnum(2, response_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    if (attach_ != null) {
      output.writeMessage(50, getAttach());
    }
    if (requestChannels_ != null) {
      output.writeMessage(51, getRequestChannels());
    }
    if (attachChannels_ != null) {
      output.writeMessage(100, getAttachChannels());
    }
    if (handoverData_ != null) {
      output.writeMessage(101, getHandoverData());
    }
    if (heartbeat_ != null) {
      output.writeMessage(102, getHeartbeat());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (command_ != com.fleetmgr.interfaces.facade.control.Command.UNDEFINED_CMD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, command_);
    }
    if (response_ != com.fleetmgr.interfaces.facade.control.Response.UNDEFINED_RSP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, response_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    if (attach_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(50, getAttach());
    }
    if (requestChannels_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(51, getRequestChannels());
    }
    if (attachChannels_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, getAttachChannels());
    }
    if (handoverData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(101, getHandoverData());
    }
    if (heartbeat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(102, getHeartbeat());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fleetmgr.interfaces.facade.control.ClientMessage)) {
      return super.equals(obj);
    }
    com.fleetmgr.interfaces.facade.control.ClientMessage other = (com.fleetmgr.interfaces.facade.control.ClientMessage) obj;

    boolean result = true;
    result = result && command_ == other.command_;
    result = result && response_ == other.response_;
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (hasAttach() == other.hasAttach());
    if (hasAttach()) {
      result = result && getAttach()
          .equals(other.getAttach());
    }
    result = result && (hasRequestChannels() == other.hasRequestChannels());
    if (hasRequestChannels()) {
      result = result && getRequestChannels()
          .equals(other.getRequestChannels());
    }
    result = result && (hasAttachChannels() == other.hasAttachChannels());
    if (hasAttachChannels()) {
      result = result && getAttachChannels()
          .equals(other.getAttachChannels());
    }
    result = result && (hasHandoverData() == other.hasHandoverData());
    if (hasHandoverData()) {
      result = result && getHandoverData()
          .equals(other.getHandoverData());
    }
    result = result && (hasHeartbeat() == other.hasHeartbeat());
    if (hasHeartbeat()) {
      result = result && getHeartbeat()
          .equals(other.getHeartbeat());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + response_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasAttach()) {
      hash = (37 * hash) + ATTACH_FIELD_NUMBER;
      hash = (53 * hash) + getAttach().hashCode();
    }
    if (hasRequestChannels()) {
      hash = (37 * hash) + REQUESTCHANNELS_FIELD_NUMBER;
      hash = (53 * hash) + getRequestChannels().hashCode();
    }
    if (hasAttachChannels()) {
      hash = (37 * hash) + ATTACHCHANNELS_FIELD_NUMBER;
      hash = (53 * hash) + getAttachChannels().hashCode();
    }
    if (hasHandoverData()) {
      hash = (37 * hash) + HANDOVERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getHandoverData().hashCode();
    }
    if (hasHeartbeat()) {
      hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + getHeartbeat().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.facade.control.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fleetmgr.interfaces.facade.control.ClientMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fleetmgr.interfaces.facade.control.ClientMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fleetmgr.interfaces.facade.control.ClientMessage)
      com.fleetmgr.interfaces.facade.control.ClientMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fleetmgr.interfaces.facade.control.ClientMessage.class, com.fleetmgr.interfaces.facade.control.ClientMessage.Builder.class);
    }

    // Construct using com.fleetmgr.interfaces.facade.control.ClientMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      command_ = 0;

      response_ = 0;

      message_ = "";

      if (attachBuilder_ == null) {
        attach_ = null;
      } else {
        attach_ = null;
        attachBuilder_ = null;
      }
      if (requestChannelsBuilder_ == null) {
        requestChannels_ = null;
      } else {
        requestChannels_ = null;
        requestChannelsBuilder_ = null;
      }
      if (attachChannelsBuilder_ == null) {
        attachChannels_ = null;
      } else {
        attachChannels_ = null;
        attachChannelsBuilder_ = null;
      }
      if (handoverDataBuilder_ == null) {
        handoverData_ = null;
      } else {
        handoverData_ = null;
        handoverDataBuilder_ = null;
      }
      if (heartbeatBuilder_ == null) {
        heartbeat_ = null;
      } else {
        heartbeat_ = null;
        heartbeatBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_descriptor;
    }

    public com.fleetmgr.interfaces.facade.control.ClientMessage getDefaultInstanceForType() {
      return com.fleetmgr.interfaces.facade.control.ClientMessage.getDefaultInstance();
    }

    public com.fleetmgr.interfaces.facade.control.ClientMessage build() {
      com.fleetmgr.interfaces.facade.control.ClientMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.fleetmgr.interfaces.facade.control.ClientMessage buildPartial() {
      com.fleetmgr.interfaces.facade.control.ClientMessage result = new com.fleetmgr.interfaces.facade.control.ClientMessage(this);
      result.command_ = command_;
      result.response_ = response_;
      result.message_ = message_;
      if (attachBuilder_ == null) {
        result.attach_ = attach_;
      } else {
        result.attach_ = attachBuilder_.build();
      }
      if (requestChannelsBuilder_ == null) {
        result.requestChannels_ = requestChannels_;
      } else {
        result.requestChannels_ = requestChannelsBuilder_.build();
      }
      if (attachChannelsBuilder_ == null) {
        result.attachChannels_ = attachChannels_;
      } else {
        result.attachChannels_ = attachChannelsBuilder_.build();
      }
      if (handoverDataBuilder_ == null) {
        result.handoverData_ = handoverData_;
      } else {
        result.handoverData_ = handoverDataBuilder_.build();
      }
      if (heartbeatBuilder_ == null) {
        result.heartbeat_ = heartbeat_;
      } else {
        result.heartbeat_ = heartbeatBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fleetmgr.interfaces.facade.control.ClientMessage) {
        return mergeFrom((com.fleetmgr.interfaces.facade.control.ClientMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fleetmgr.interfaces.facade.control.ClientMessage other) {
      if (other == com.fleetmgr.interfaces.facade.control.ClientMessage.getDefaultInstance()) return this;
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (other.response_ != 0) {
        setResponseValue(other.getResponseValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasAttach()) {
        mergeAttach(other.getAttach());
      }
      if (other.hasRequestChannels()) {
        mergeRequestChannels(other.getRequestChannels());
      }
      if (other.hasAttachChannels()) {
        mergeAttachChannels(other.getAttachChannels());
      }
      if (other.hasHandoverData()) {
        mergeHandoverData(other.getHandoverData());
      }
      if (other.hasHeartbeat()) {
        mergeHeartbeat(other.getHeartbeat());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fleetmgr.interfaces.facade.control.ClientMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fleetmgr.interfaces.facade.control.ClientMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int command_ = 0;
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public Builder setCommandValue(int value) {
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public com.fleetmgr.interfaces.facade.control.Command getCommand() {
      com.fleetmgr.interfaces.facade.control.Command result = com.fleetmgr.interfaces.facade.control.Command.valueOf(command_);
      return result == null ? com.fleetmgr.interfaces.facade.control.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public Builder setCommand(com.fleetmgr.interfaces.facade.control.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private int response_ = 0;
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public Builder setResponseValue(int value) {
      response_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public com.fleetmgr.interfaces.facade.control.Response getResponse() {
      com.fleetmgr.interfaces.facade.control.Response result = com.fleetmgr.interfaces.facade.control.Response.valueOf(response_);
      return result == null ? com.fleetmgr.interfaces.facade.control.Response.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public Builder setResponse(com.fleetmgr.interfaces.facade.control.Response value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      response_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public Builder clearResponse() {
      
      response_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.fleetmgr.interfaces.facade.control.SetupRequest attach_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.SetupRequest, com.fleetmgr.interfaces.facade.control.SetupRequest.Builder, com.fleetmgr.interfaces.facade.control.SetupRequestOrBuilder> attachBuilder_;
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public boolean hasAttach() {
      return attachBuilder_ != null || attach_ != null;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public com.fleetmgr.interfaces.facade.control.SetupRequest getAttach() {
      if (attachBuilder_ == null) {
        return attach_ == null ? com.fleetmgr.interfaces.facade.control.SetupRequest.getDefaultInstance() : attach_;
      } else {
        return attachBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public Builder setAttach(com.fleetmgr.interfaces.facade.control.SetupRequest value) {
      if (attachBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attach_ = value;
        onChanged();
      } else {
        attachBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public Builder setAttach(
        com.fleetmgr.interfaces.facade.control.SetupRequest.Builder builderForValue) {
      if (attachBuilder_ == null) {
        attach_ = builderForValue.build();
        onChanged();
      } else {
        attachBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public Builder mergeAttach(com.fleetmgr.interfaces.facade.control.SetupRequest value) {
      if (attachBuilder_ == null) {
        if (attach_ != null) {
          attach_ =
            com.fleetmgr.interfaces.facade.control.SetupRequest.newBuilder(attach_).mergeFrom(value).buildPartial();
        } else {
          attach_ = value;
        }
        onChanged();
      } else {
        attachBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public Builder clearAttach() {
      if (attachBuilder_ == null) {
        attach_ = null;
        onChanged();
      } else {
        attach_ = null;
        attachBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public com.fleetmgr.interfaces.facade.control.SetupRequest.Builder getAttachBuilder() {
      
      onChanged();
      return getAttachFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    public com.fleetmgr.interfaces.facade.control.SetupRequestOrBuilder getAttachOrBuilder() {
      if (attachBuilder_ != null) {
        return attachBuilder_.getMessageOrBuilder();
      } else {
        return attach_ == null ?
            com.fleetmgr.interfaces.facade.control.SetupRequest.getDefaultInstance() : attach_;
      }
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupRequest attach = 50;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.SetupRequest, com.fleetmgr.interfaces.facade.control.SetupRequest.Builder, com.fleetmgr.interfaces.facade.control.SetupRequestOrBuilder> 
        getAttachFieldBuilder() {
      if (attachBuilder_ == null) {
        attachBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.facade.control.SetupRequest, com.fleetmgr.interfaces.facade.control.SetupRequest.Builder, com.fleetmgr.interfaces.facade.control.SetupRequestOrBuilder>(
                getAttach(),
                getParentForChildren(),
                isClean());
        attach_ = null;
      }
      return attachBuilder_;
    }

    private com.fleetmgr.interfaces.AddChannelsRequest requestChannels_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.AddChannelsRequest, com.fleetmgr.interfaces.AddChannelsRequest.Builder, com.fleetmgr.interfaces.AddChannelsRequestOrBuilder> requestChannelsBuilder_;
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public boolean hasRequestChannels() {
      return requestChannelsBuilder_ != null || requestChannels_ != null;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public com.fleetmgr.interfaces.AddChannelsRequest getRequestChannels() {
      if (requestChannelsBuilder_ == null) {
        return requestChannels_ == null ? com.fleetmgr.interfaces.AddChannelsRequest.getDefaultInstance() : requestChannels_;
      } else {
        return requestChannelsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public Builder setRequestChannels(com.fleetmgr.interfaces.AddChannelsRequest value) {
      if (requestChannelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestChannels_ = value;
        onChanged();
      } else {
        requestChannelsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public Builder setRequestChannels(
        com.fleetmgr.interfaces.AddChannelsRequest.Builder builderForValue) {
      if (requestChannelsBuilder_ == null) {
        requestChannels_ = builderForValue.build();
        onChanged();
      } else {
        requestChannelsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public Builder mergeRequestChannels(com.fleetmgr.interfaces.AddChannelsRequest value) {
      if (requestChannelsBuilder_ == null) {
        if (requestChannels_ != null) {
          requestChannels_ =
            com.fleetmgr.interfaces.AddChannelsRequest.newBuilder(requestChannels_).mergeFrom(value).buildPartial();
        } else {
          requestChannels_ = value;
        }
        onChanged();
      } else {
        requestChannelsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public Builder clearRequestChannels() {
      if (requestChannelsBuilder_ == null) {
        requestChannels_ = null;
        onChanged();
      } else {
        requestChannels_ = null;
        requestChannelsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public com.fleetmgr.interfaces.AddChannelsRequest.Builder getRequestChannelsBuilder() {
      
      onChanged();
      return getRequestChannelsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    public com.fleetmgr.interfaces.AddChannelsRequestOrBuilder getRequestChannelsOrBuilder() {
      if (requestChannelsBuilder_ != null) {
        return requestChannelsBuilder_.getMessageOrBuilder();
      } else {
        return requestChannels_ == null ?
            com.fleetmgr.interfaces.AddChannelsRequest.getDefaultInstance() : requestChannels_;
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsRequest requestChannels = 51;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.AddChannelsRequest, com.fleetmgr.interfaces.AddChannelsRequest.Builder, com.fleetmgr.interfaces.AddChannelsRequestOrBuilder> 
        getRequestChannelsFieldBuilder() {
      if (requestChannelsBuilder_ == null) {
        requestChannelsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.AddChannelsRequest, com.fleetmgr.interfaces.AddChannelsRequest.Builder, com.fleetmgr.interfaces.AddChannelsRequestOrBuilder>(
                getRequestChannels(),
                getParentForChildren(),
                isClean());
        requestChannels_ = null;
      }
      return requestChannelsBuilder_;
    }

    private com.fleetmgr.interfaces.ChannelsResponse attachChannels_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.ChannelsResponse, com.fleetmgr.interfaces.ChannelsResponse.Builder, com.fleetmgr.interfaces.ChannelsResponseOrBuilder> attachChannelsBuilder_;
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public boolean hasAttachChannels() {
      return attachChannelsBuilder_ != null || attachChannels_ != null;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public com.fleetmgr.interfaces.ChannelsResponse getAttachChannels() {
      if (attachChannelsBuilder_ == null) {
        return attachChannels_ == null ? com.fleetmgr.interfaces.ChannelsResponse.getDefaultInstance() : attachChannels_;
      } else {
        return attachChannelsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public Builder setAttachChannels(com.fleetmgr.interfaces.ChannelsResponse value) {
      if (attachChannelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attachChannels_ = value;
        onChanged();
      } else {
        attachChannelsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public Builder setAttachChannels(
        com.fleetmgr.interfaces.ChannelsResponse.Builder builderForValue) {
      if (attachChannelsBuilder_ == null) {
        attachChannels_ = builderForValue.build();
        onChanged();
      } else {
        attachChannelsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public Builder mergeAttachChannels(com.fleetmgr.interfaces.ChannelsResponse value) {
      if (attachChannelsBuilder_ == null) {
        if (attachChannels_ != null) {
          attachChannels_ =
            com.fleetmgr.interfaces.ChannelsResponse.newBuilder(attachChannels_).mergeFrom(value).buildPartial();
        } else {
          attachChannels_ = value;
        }
        onChanged();
      } else {
        attachChannelsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public Builder clearAttachChannels() {
      if (attachChannelsBuilder_ == null) {
        attachChannels_ = null;
        onChanged();
      } else {
        attachChannels_ = null;
        attachChannelsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public com.fleetmgr.interfaces.ChannelsResponse.Builder getAttachChannelsBuilder() {
      
      onChanged();
      return getAttachChannelsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    public com.fleetmgr.interfaces.ChannelsResponseOrBuilder getAttachChannelsOrBuilder() {
      if (attachChannelsBuilder_ != null) {
        return attachChannelsBuilder_.getMessageOrBuilder();
      } else {
        return attachChannels_ == null ?
            com.fleetmgr.interfaces.ChannelsResponse.getDefaultInstance() : attachChannels_;
      }
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.ChannelsResponse attachChannels = 100;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.ChannelsResponse, com.fleetmgr.interfaces.ChannelsResponse.Builder, com.fleetmgr.interfaces.ChannelsResponseOrBuilder> 
        getAttachChannelsFieldBuilder() {
      if (attachChannelsBuilder_ == null) {
        attachChannelsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.ChannelsResponse, com.fleetmgr.interfaces.ChannelsResponse.Builder, com.fleetmgr.interfaces.ChannelsResponseOrBuilder>(
                getAttachChannels(),
                getParentForChildren(),
                isClean());
        attachChannels_ = null;
      }
      return attachChannelsBuilder_;
    }

    private com.fleetmgr.interfaces.HandoverData handoverData_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.HandoverData, com.fleetmgr.interfaces.HandoverData.Builder, com.fleetmgr.interfaces.HandoverDataOrBuilder> handoverDataBuilder_;
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public boolean hasHandoverData() {
      return handoverDataBuilder_ != null || handoverData_ != null;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public com.fleetmgr.interfaces.HandoverData getHandoverData() {
      if (handoverDataBuilder_ == null) {
        return handoverData_ == null ? com.fleetmgr.interfaces.HandoverData.getDefaultInstance() : handoverData_;
      } else {
        return handoverDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public Builder setHandoverData(com.fleetmgr.interfaces.HandoverData value) {
      if (handoverDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        handoverData_ = value;
        onChanged();
      } else {
        handoverDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public Builder setHandoverData(
        com.fleetmgr.interfaces.HandoverData.Builder builderForValue) {
      if (handoverDataBuilder_ == null) {
        handoverData_ = builderForValue.build();
        onChanged();
      } else {
        handoverDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public Builder mergeHandoverData(com.fleetmgr.interfaces.HandoverData value) {
      if (handoverDataBuilder_ == null) {
        if (handoverData_ != null) {
          handoverData_ =
            com.fleetmgr.interfaces.HandoverData.newBuilder(handoverData_).mergeFrom(value).buildPartial();
        } else {
          handoverData_ = value;
        }
        onChanged();
      } else {
        handoverDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public Builder clearHandoverData() {
      if (handoverDataBuilder_ == null) {
        handoverData_ = null;
        onChanged();
      } else {
        handoverData_ = null;
        handoverDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public com.fleetmgr.interfaces.HandoverData.Builder getHandoverDataBuilder() {
      
      onChanged();
      return getHandoverDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    public com.fleetmgr.interfaces.HandoverDataOrBuilder getHandoverDataOrBuilder() {
      if (handoverDataBuilder_ != null) {
        return handoverDataBuilder_.getMessageOrBuilder();
      } else {
        return handoverData_ == null ?
            com.fleetmgr.interfaces.HandoverData.getDefaultInstance() : handoverData_;
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 101;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.HandoverData, com.fleetmgr.interfaces.HandoverData.Builder, com.fleetmgr.interfaces.HandoverDataOrBuilder> 
        getHandoverDataFieldBuilder() {
      if (handoverDataBuilder_ == null) {
        handoverDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.HandoverData, com.fleetmgr.interfaces.HandoverData.Builder, com.fleetmgr.interfaces.HandoverDataOrBuilder>(
                getHandoverData(),
                getParentForChildren(),
                isClean());
        handoverData_ = null;
      }
      return handoverDataBuilder_;
    }

    private com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.HeartbeatResponse, com.fleetmgr.interfaces.facade.control.HeartbeatResponse.Builder, com.fleetmgr.interfaces.facade.control.HeartbeatResponseOrBuilder> heartbeatBuilder_;
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public boolean hasHeartbeat() {
      return heartbeatBuilder_ != null || heartbeat_ != null;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public com.fleetmgr.interfaces.facade.control.HeartbeatResponse getHeartbeat() {
      if (heartbeatBuilder_ == null) {
        return heartbeat_ == null ? com.fleetmgr.interfaces.facade.control.HeartbeatResponse.getDefaultInstance() : heartbeat_;
      } else {
        return heartbeatBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public Builder setHeartbeat(com.fleetmgr.interfaces.facade.control.HeartbeatResponse value) {
      if (heartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        heartbeat_ = value;
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public Builder setHeartbeat(
        com.fleetmgr.interfaces.facade.control.HeartbeatResponse.Builder builderForValue) {
      if (heartbeatBuilder_ == null) {
        heartbeat_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public Builder mergeHeartbeat(com.fleetmgr.interfaces.facade.control.HeartbeatResponse value) {
      if (heartbeatBuilder_ == null) {
        if (heartbeat_ != null) {
          heartbeat_ =
            com.fleetmgr.interfaces.facade.control.HeartbeatResponse.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
        } else {
          heartbeat_ = value;
        }
        onChanged();
      } else {
        heartbeatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public Builder clearHeartbeat() {
      if (heartbeatBuilder_ == null) {
        heartbeat_ = null;
        onChanged();
      } else {
        heartbeat_ = null;
        heartbeatBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public com.fleetmgr.interfaces.facade.control.HeartbeatResponse.Builder getHeartbeatBuilder() {
      
      onChanged();
      return getHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    public com.fleetmgr.interfaces.facade.control.HeartbeatResponseOrBuilder getHeartbeatOrBuilder() {
      if (heartbeatBuilder_ != null) {
        return heartbeatBuilder_.getMessageOrBuilder();
      } else {
        return heartbeat_ == null ?
            com.fleetmgr.interfaces.facade.control.HeartbeatResponse.getDefaultInstance() : heartbeat_;
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatResponse heartbeat = 102;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.HeartbeatResponse, com.fleetmgr.interfaces.facade.control.HeartbeatResponse.Builder, com.fleetmgr.interfaces.facade.control.HeartbeatResponseOrBuilder> 
        getHeartbeatFieldBuilder() {
      if (heartbeatBuilder_ == null) {
        heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.facade.control.HeartbeatResponse, com.fleetmgr.interfaces.facade.control.HeartbeatResponse.Builder, com.fleetmgr.interfaces.facade.control.HeartbeatResponseOrBuilder>(
                getHeartbeat(),
                getParentForChildren(),
                isClean());
        heartbeat_ = null;
      }
      return heartbeatBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.fleetmgr.interfaces.facade.control.ClientMessage)
  }

  // @@protoc_insertion_point(class_scope:com.fleetmgr.interfaces.facade.control.ClientMessage)
  private static final com.fleetmgr.interfaces.facade.control.ClientMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fleetmgr.interfaces.facade.control.ClientMessage();
  }

  public static com.fleetmgr.interfaces.facade.control.ClientMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientMessage>
      PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
    public ClientMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientMessage> getParserForType() {
    return PARSER;
  }

  public com.fleetmgr.interfaces.facade.control.ClientMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

