// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/facade_service.proto

package com.fleetmgr.interfaces.facade.control;

/**
 * Protobuf enum {@code com.fleetmgr.interfaces.facade.control.Command}
 */
public enum Command
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNDEFINED_CMD = 0;</code>
   */
  UNDEFINED_CMD(0),
  /**
   * <code>HEARTBEAT = 1;</code>
   */
  HEARTBEAT(1),
  /**
   * <code>SETUP = 2;</code>
   */
  SETUP(2),
  /**
   * <code>RELEASE = 3;</code>
   */
  RELEASE(3),
  /**
   * <code>ADD_CHANNELS = 11;</code>
   */
  ADD_CHANNELS(11),
  /**
   * <code>REMOVE_CHANNELS = 12;</code>
   */
  REMOVE_CHANNELS(12),
  /**
   * <code>ATTACH_CHANNELS = 13;</code>
   */
  ATTACH_CHANNELS(13),
  /**
   * <code>RELEASE_CHANNELS = 14;</code>
   */
  RELEASE_CHANNELS(14),
  /**
   * <code>CHANNELS_READY = 15;</code>
   */
  CHANNELS_READY(15),
  /**
   * <code>REQUEST_CONTROL = 21;</code>
   */
  REQUEST_CONTROL(21),
  /**
   * <code>RELEASE_CONTROL = 22;</code>
   */
  RELEASE_CONTROL(22),
  /**
   * <code>CONTROL_RELEASED = 23;</code>
   */
  CONTROL_RELEASED(23),
  /**
   * <code>CONTROL_READY = 24;</code>
   */
  CONTROL_READY(24),
  /**
   * <code>OPERATION_ENDED = 31;</code>
   */
  OPERATION_ENDED(31),
  /**
   * <code>DEVICE_UNREACHABLE = 41;</code>
   */
  DEVICE_UNREACHABLE(41),
  /**
   * <code>LEADER_UNREACHABLE = 42;</code>
   */
  LEADER_UNREACHABLE(42),
  /**
   * <code>RECOVERY = 43;</code>
   */
  RECOVERY(43),
  /**
   * <code>DEVICE_RECOVERED = 44;</code>
   */
  DEVICE_RECOVERED(44),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNDEFINED_CMD = 0;</code>
   */
  public static final int UNDEFINED_CMD_VALUE = 0;
  /**
   * <code>HEARTBEAT = 1;</code>
   */
  public static final int HEARTBEAT_VALUE = 1;
  /**
   * <code>SETUP = 2;</code>
   */
  public static final int SETUP_VALUE = 2;
  /**
   * <code>RELEASE = 3;</code>
   */
  public static final int RELEASE_VALUE = 3;
  /**
   * <code>ADD_CHANNELS = 11;</code>
   */
  public static final int ADD_CHANNELS_VALUE = 11;
  /**
   * <code>REMOVE_CHANNELS = 12;</code>
   */
  public static final int REMOVE_CHANNELS_VALUE = 12;
  /**
   * <code>ATTACH_CHANNELS = 13;</code>
   */
  public static final int ATTACH_CHANNELS_VALUE = 13;
  /**
   * <code>RELEASE_CHANNELS = 14;</code>
   */
  public static final int RELEASE_CHANNELS_VALUE = 14;
  /**
   * <code>CHANNELS_READY = 15;</code>
   */
  public static final int CHANNELS_READY_VALUE = 15;
  /**
   * <code>REQUEST_CONTROL = 21;</code>
   */
  public static final int REQUEST_CONTROL_VALUE = 21;
  /**
   * <code>RELEASE_CONTROL = 22;</code>
   */
  public static final int RELEASE_CONTROL_VALUE = 22;
  /**
   * <code>CONTROL_RELEASED = 23;</code>
   */
  public static final int CONTROL_RELEASED_VALUE = 23;
  /**
   * <code>CONTROL_READY = 24;</code>
   */
  public static final int CONTROL_READY_VALUE = 24;
  /**
   * <code>OPERATION_ENDED = 31;</code>
   */
  public static final int OPERATION_ENDED_VALUE = 31;
  /**
   * <code>DEVICE_UNREACHABLE = 41;</code>
   */
  public static final int DEVICE_UNREACHABLE_VALUE = 41;
  /**
   * <code>LEADER_UNREACHABLE = 42;</code>
   */
  public static final int LEADER_UNREACHABLE_VALUE = 42;
  /**
   * <code>RECOVERY = 43;</code>
   */
  public static final int RECOVERY_VALUE = 43;
  /**
   * <code>DEVICE_RECOVERED = 44;</code>
   */
  public static final int DEVICE_RECOVERED_VALUE = 44;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Command valueOf(int value) {
    return forNumber(value);
  }

  public static Command forNumber(int value) {
    switch (value) {
      case 0: return UNDEFINED_CMD;
      case 1: return HEARTBEAT;
      case 2: return SETUP;
      case 3: return RELEASE;
      case 11: return ADD_CHANNELS;
      case 12: return REMOVE_CHANNELS;
      case 13: return ATTACH_CHANNELS;
      case 14: return RELEASE_CHANNELS;
      case 15: return CHANNELS_READY;
      case 21: return REQUEST_CONTROL;
      case 22: return RELEASE_CONTROL;
      case 23: return CONTROL_RELEASED;
      case 24: return CONTROL_READY;
      case 31: return OPERATION_ENDED;
      case 41: return DEVICE_UNREACHABLE;
      case 42: return LEADER_UNREACHABLE;
      case 43: return RECOVERY;
      case 44: return DEVICE_RECOVERED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Command>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Command> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Command>() {
          public Command findValueByNumber(int number) {
            return Command.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final Command[] VALUES = values();

  public static Command valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Command(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.fleetmgr.interfaces.facade.control.Command)
}

