// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/facade_service.proto

package com.fleetmgr.interfaces.facade.control;

public interface ControlMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.facade.control.ControlMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  int getCommandValue();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  com.fleetmgr.interfaces.facade.control.Command getCommand();

  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  int getResponseValue();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  com.fleetmgr.interfaces.facade.control.Response getResponse();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
   */
  boolean hasAttach();
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
   */
  com.fleetmgr.interfaces.facade.control.SetupResponse getAttach();
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
   */
  com.fleetmgr.interfaces.facade.control.SetupResponseOrBuilder getAttachOrBuilder();

  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
   */
  boolean hasRequestChannels();
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
   */
  com.fleetmgr.interfaces.AddChannelsResponse getRequestChannels();
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
   */
  com.fleetmgr.interfaces.AddChannelsResponseOrBuilder getRequestChannelsOrBuilder();

  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
   */
  boolean hasHandoverData();
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
   */
  com.fleetmgr.interfaces.HandoverData getHandoverData();
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
   */
  com.fleetmgr.interfaces.HandoverDataOrBuilder getHandoverDataOrBuilder();

  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
   */
  boolean hasAttachChannels();
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
   */
  com.fleetmgr.interfaces.AttachChannelsRequest getAttachChannels();
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
   */
  com.fleetmgr.interfaces.AttachChannelsRequestOrBuilder getAttachChannelsOrBuilder();

  /**
   * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
   */
  boolean hasChannels();
  /**
   * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
   */
  com.fleetmgr.interfaces.ChannelsResponse getChannels();
  /**
   * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
   */
  com.fleetmgr.interfaces.ChannelsResponseOrBuilder getChannelsOrBuilder();

  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
   */
  boolean hasHeartbeat();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
   */
  com.fleetmgr.interfaces.facade.control.HeartbeatRequest getHeartbeat();
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
   */
  com.fleetmgr.interfaces.facade.control.HeartbeatRequestOrBuilder getHeartbeatOrBuilder();
}
