// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/facade_service.proto

package com.fleetmgr.interfaces.facade.control;

/**
 * Protobuf type {@code com.fleetmgr.interfaces.facade.control.ControlMessage}
 */
public  final class ControlMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fleetmgr.interfaces.facade.control.ControlMessage)
    ControlMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ControlMessage.newBuilder() to construct.
  private ControlMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ControlMessage() {
    command_ = 0;
    response_ = 0;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ControlMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            response_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 402: {
            com.fleetmgr.interfaces.facade.control.SetupResponse.Builder subBuilder = null;
            if (attach_ != null) {
              subBuilder = attach_.toBuilder();
            }
            attach_ = input.readMessage(com.fleetmgr.interfaces.facade.control.SetupResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(attach_);
              attach_ = subBuilder.buildPartial();
            }

            break;
          }
          case 410: {
            com.fleetmgr.interfaces.AddChannelsResponse.Builder subBuilder = null;
            if (requestChannels_ != null) {
              subBuilder = requestChannels_.toBuilder();
            }
            requestChannels_ = input.readMessage(com.fleetmgr.interfaces.AddChannelsResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestChannels_);
              requestChannels_ = subBuilder.buildPartial();
            }

            break;
          }
          case 418: {
            com.fleetmgr.interfaces.HandoverData.Builder subBuilder = null;
            if (handoverData_ != null) {
              subBuilder = handoverData_.toBuilder();
            }
            handoverData_ = input.readMessage(com.fleetmgr.interfaces.HandoverData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(handoverData_);
              handoverData_ = subBuilder.buildPartial();
            }

            break;
          }
          case 802: {
            com.fleetmgr.interfaces.AttachChannelsRequest.Builder subBuilder = null;
            if (attachChannels_ != null) {
              subBuilder = attachChannels_.toBuilder();
            }
            attachChannels_ = input.readMessage(com.fleetmgr.interfaces.AttachChannelsRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(attachChannels_);
              attachChannels_ = subBuilder.buildPartial();
            }

            break;
          }
          case 810: {
            com.fleetmgr.interfaces.ChannelsResponse.Builder subBuilder = null;
            if (channels_ != null) {
              subBuilder = channels_.toBuilder();
            }
            channels_ = input.readMessage(com.fleetmgr.interfaces.ChannelsResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(channels_);
              channels_ = subBuilder.buildPartial();
            }

            break;
          }
          case 818: {
            com.fleetmgr.interfaces.facade.control.HeartbeatRequest.Builder subBuilder = null;
            if (heartbeat_ != null) {
              subBuilder = heartbeat_.toBuilder();
            }
            heartbeat_ = input.readMessage(com.fleetmgr.interfaces.facade.control.HeartbeatRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(heartbeat_);
              heartbeat_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fleetmgr.interfaces.facade.control.ControlMessage.class, com.fleetmgr.interfaces.facade.control.ControlMessage.Builder.class);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  private int command_;
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
   */
  public com.fleetmgr.interfaces.facade.control.Command getCommand() {
    com.fleetmgr.interfaces.facade.control.Command result = com.fleetmgr.interfaces.facade.control.Command.valueOf(command_);
    return result == null ? com.fleetmgr.interfaces.facade.control.Command.UNRECOGNIZED : result;
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  private int response_;
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  public int getResponseValue() {
    return response_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
   */
  public com.fleetmgr.interfaces.facade.control.Response getResponse() {
    com.fleetmgr.interfaces.facade.control.Response result = com.fleetmgr.interfaces.facade.control.Response.valueOf(response_);
    return result == null ? com.fleetmgr.interfaces.facade.control.Response.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTACH_FIELD_NUMBER = 50;
  private com.fleetmgr.interfaces.facade.control.SetupResponse attach_;
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
   */
  public boolean hasAttach() {
    return attach_ != null;
  }
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
   */
  public com.fleetmgr.interfaces.facade.control.SetupResponse getAttach() {
    return attach_ == null ? com.fleetmgr.interfaces.facade.control.SetupResponse.getDefaultInstance() : attach_;
  }
  /**
   * <pre>
   * responses, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
   */
  public com.fleetmgr.interfaces.facade.control.SetupResponseOrBuilder getAttachOrBuilder() {
    return getAttach();
  }

  public static final int REQUESTCHANNELS_FIELD_NUMBER = 51;
  private com.fleetmgr.interfaces.AddChannelsResponse requestChannels_;
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
   */
  public boolean hasRequestChannels() {
    return requestChannels_ != null;
  }
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
   */
  public com.fleetmgr.interfaces.AddChannelsResponse getRequestChannels() {
    return requestChannels_ == null ? com.fleetmgr.interfaces.AddChannelsResponse.getDefaultInstance() : requestChannels_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
   */
  public com.fleetmgr.interfaces.AddChannelsResponseOrBuilder getRequestChannelsOrBuilder() {
    return getRequestChannels();
  }

  public static final int HANDOVERDATA_FIELD_NUMBER = 52;
  private com.fleetmgr.interfaces.HandoverData handoverData_;
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
   */
  public boolean hasHandoverData() {
    return handoverData_ != null;
  }
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
   */
  public com.fleetmgr.interfaces.HandoverData getHandoverData() {
    return handoverData_ == null ? com.fleetmgr.interfaces.HandoverData.getDefaultInstance() : handoverData_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
   */
  public com.fleetmgr.interfaces.HandoverDataOrBuilder getHandoverDataOrBuilder() {
    return getHandoverData();
  }

  public static final int ATTACHCHANNELS_FIELD_NUMBER = 100;
  private com.fleetmgr.interfaces.AttachChannelsRequest attachChannels_;
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
   */
  public boolean hasAttachChannels() {
    return attachChannels_ != null;
  }
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
   */
  public com.fleetmgr.interfaces.AttachChannelsRequest getAttachChannels() {
    return attachChannels_ == null ? com.fleetmgr.interfaces.AttachChannelsRequest.getDefaultInstance() : attachChannels_;
  }
  /**
   * <pre>
   * requests, defined by Command/Response fields
   * </pre>
   *
   * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
   */
  public com.fleetmgr.interfaces.AttachChannelsRequestOrBuilder getAttachChannelsOrBuilder() {
    return getAttachChannels();
  }

  public static final int CHANNELS_FIELD_NUMBER = 101;
  private com.fleetmgr.interfaces.ChannelsResponse channels_;
  /**
   * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
   */
  public boolean hasChannels() {
    return channels_ != null;
  }
  /**
   * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
   */
  public com.fleetmgr.interfaces.ChannelsResponse getChannels() {
    return channels_ == null ? com.fleetmgr.interfaces.ChannelsResponse.getDefaultInstance() : channels_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
   */
  public com.fleetmgr.interfaces.ChannelsResponseOrBuilder getChannelsOrBuilder() {
    return getChannels();
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 102;
  private com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat_;
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
   */
  public boolean hasHeartbeat() {
    return heartbeat_ != null;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
   */
  public com.fleetmgr.interfaces.facade.control.HeartbeatRequest getHeartbeat() {
    return heartbeat_ == null ? com.fleetmgr.interfaces.facade.control.HeartbeatRequest.getDefaultInstance() : heartbeat_;
  }
  /**
   * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
   */
  public com.fleetmgr.interfaces.facade.control.HeartbeatRequestOrBuilder getHeartbeatOrBuilder() {
    return getHeartbeat();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (command_ != com.fleetmgr.interfaces.facade.control.Command.UNDEFINED_CMD.getNumber()) {
      output.writeEnum(1, command_);
    }
    if (response_ != com.fleetmgr.interfaces.facade.control.Response.UNDEFINED_RSP.getNumber()) {
      output.writeEnum(2, response_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    if (attach_ != null) {
      output.writeMessage(50, getAttach());
    }
    if (requestChannels_ != null) {
      output.writeMessage(51, getRequestChannels());
    }
    if (handoverData_ != null) {
      output.writeMessage(52, getHandoverData());
    }
    if (attachChannels_ != null) {
      output.writeMessage(100, getAttachChannels());
    }
    if (channels_ != null) {
      output.writeMessage(101, getChannels());
    }
    if (heartbeat_ != null) {
      output.writeMessage(102, getHeartbeat());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (command_ != com.fleetmgr.interfaces.facade.control.Command.UNDEFINED_CMD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, command_);
    }
    if (response_ != com.fleetmgr.interfaces.facade.control.Response.UNDEFINED_RSP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, response_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    if (attach_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(50, getAttach());
    }
    if (requestChannels_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(51, getRequestChannels());
    }
    if (handoverData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(52, getHandoverData());
    }
    if (attachChannels_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, getAttachChannels());
    }
    if (channels_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(101, getChannels());
    }
    if (heartbeat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(102, getHeartbeat());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fleetmgr.interfaces.facade.control.ControlMessage)) {
      return super.equals(obj);
    }
    com.fleetmgr.interfaces.facade.control.ControlMessage other = (com.fleetmgr.interfaces.facade.control.ControlMessage) obj;

    boolean result = true;
    result = result && command_ == other.command_;
    result = result && response_ == other.response_;
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (hasAttach() == other.hasAttach());
    if (hasAttach()) {
      result = result && getAttach()
          .equals(other.getAttach());
    }
    result = result && (hasRequestChannels() == other.hasRequestChannels());
    if (hasRequestChannels()) {
      result = result && getRequestChannels()
          .equals(other.getRequestChannels());
    }
    result = result && (hasHandoverData() == other.hasHandoverData());
    if (hasHandoverData()) {
      result = result && getHandoverData()
          .equals(other.getHandoverData());
    }
    result = result && (hasAttachChannels() == other.hasAttachChannels());
    if (hasAttachChannels()) {
      result = result && getAttachChannels()
          .equals(other.getAttachChannels());
    }
    result = result && (hasChannels() == other.hasChannels());
    if (hasChannels()) {
      result = result && getChannels()
          .equals(other.getChannels());
    }
    result = result && (hasHeartbeat() == other.hasHeartbeat());
    if (hasHeartbeat()) {
      result = result && getHeartbeat()
          .equals(other.getHeartbeat());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + response_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasAttach()) {
      hash = (37 * hash) + ATTACH_FIELD_NUMBER;
      hash = (53 * hash) + getAttach().hashCode();
    }
    if (hasRequestChannels()) {
      hash = (37 * hash) + REQUESTCHANNELS_FIELD_NUMBER;
      hash = (53 * hash) + getRequestChannels().hashCode();
    }
    if (hasHandoverData()) {
      hash = (37 * hash) + HANDOVERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getHandoverData().hashCode();
    }
    if (hasAttachChannels()) {
      hash = (37 * hash) + ATTACHCHANNELS_FIELD_NUMBER;
      hash = (53 * hash) + getAttachChannels().hashCode();
    }
    if (hasChannels()) {
      hash = (37 * hash) + CHANNELS_FIELD_NUMBER;
      hash = (53 * hash) + getChannels().hashCode();
    }
    if (hasHeartbeat()) {
      hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + getHeartbeat().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fleetmgr.interfaces.facade.control.ControlMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fleetmgr.interfaces.facade.control.ControlMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fleetmgr.interfaces.facade.control.ControlMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fleetmgr.interfaces.facade.control.ControlMessage)
      com.fleetmgr.interfaces.facade.control.ControlMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fleetmgr.interfaces.facade.control.ControlMessage.class, com.fleetmgr.interfaces.facade.control.ControlMessage.Builder.class);
    }

    // Construct using com.fleetmgr.interfaces.facade.control.ControlMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      command_ = 0;

      response_ = 0;

      message_ = "";

      if (attachBuilder_ == null) {
        attach_ = null;
      } else {
        attach_ = null;
        attachBuilder_ = null;
      }
      if (requestChannelsBuilder_ == null) {
        requestChannels_ = null;
      } else {
        requestChannels_ = null;
        requestChannelsBuilder_ = null;
      }
      if (handoverDataBuilder_ == null) {
        handoverData_ = null;
      } else {
        handoverData_ = null;
        handoverDataBuilder_ = null;
      }
      if (attachChannelsBuilder_ == null) {
        attachChannels_ = null;
      } else {
        attachChannels_ = null;
        attachChannelsBuilder_ = null;
      }
      if (channelsBuilder_ == null) {
        channels_ = null;
      } else {
        channels_ = null;
        channelsBuilder_ = null;
      }
      if (heartbeatBuilder_ == null) {
        heartbeat_ = null;
      } else {
        heartbeat_ = null;
        heartbeatBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_descriptor;
    }

    public com.fleetmgr.interfaces.facade.control.ControlMessage getDefaultInstanceForType() {
      return com.fleetmgr.interfaces.facade.control.ControlMessage.getDefaultInstance();
    }

    public com.fleetmgr.interfaces.facade.control.ControlMessage build() {
      com.fleetmgr.interfaces.facade.control.ControlMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.fleetmgr.interfaces.facade.control.ControlMessage buildPartial() {
      com.fleetmgr.interfaces.facade.control.ControlMessage result = new com.fleetmgr.interfaces.facade.control.ControlMessage(this);
      result.command_ = command_;
      result.response_ = response_;
      result.message_ = message_;
      if (attachBuilder_ == null) {
        result.attach_ = attach_;
      } else {
        result.attach_ = attachBuilder_.build();
      }
      if (requestChannelsBuilder_ == null) {
        result.requestChannels_ = requestChannels_;
      } else {
        result.requestChannels_ = requestChannelsBuilder_.build();
      }
      if (handoverDataBuilder_ == null) {
        result.handoverData_ = handoverData_;
      } else {
        result.handoverData_ = handoverDataBuilder_.build();
      }
      if (attachChannelsBuilder_ == null) {
        result.attachChannels_ = attachChannels_;
      } else {
        result.attachChannels_ = attachChannelsBuilder_.build();
      }
      if (channelsBuilder_ == null) {
        result.channels_ = channels_;
      } else {
        result.channels_ = channelsBuilder_.build();
      }
      if (heartbeatBuilder_ == null) {
        result.heartbeat_ = heartbeat_;
      } else {
        result.heartbeat_ = heartbeatBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fleetmgr.interfaces.facade.control.ControlMessage) {
        return mergeFrom((com.fleetmgr.interfaces.facade.control.ControlMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fleetmgr.interfaces.facade.control.ControlMessage other) {
      if (other == com.fleetmgr.interfaces.facade.control.ControlMessage.getDefaultInstance()) return this;
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (other.response_ != 0) {
        setResponseValue(other.getResponseValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasAttach()) {
        mergeAttach(other.getAttach());
      }
      if (other.hasRequestChannels()) {
        mergeRequestChannels(other.getRequestChannels());
      }
      if (other.hasHandoverData()) {
        mergeHandoverData(other.getHandoverData());
      }
      if (other.hasAttachChannels()) {
        mergeAttachChannels(other.getAttachChannels());
      }
      if (other.hasChannels()) {
        mergeChannels(other.getChannels());
      }
      if (other.hasHeartbeat()) {
        mergeHeartbeat(other.getHeartbeat());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fleetmgr.interfaces.facade.control.ControlMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fleetmgr.interfaces.facade.control.ControlMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int command_ = 0;
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public Builder setCommandValue(int value) {
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public com.fleetmgr.interfaces.facade.control.Command getCommand() {
      com.fleetmgr.interfaces.facade.control.Command result = com.fleetmgr.interfaces.facade.control.Command.valueOf(command_);
      return result == null ? com.fleetmgr.interfaces.facade.control.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public Builder setCommand(com.fleetmgr.interfaces.facade.control.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Command command = 1;</code>
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private int response_ = 0;
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public Builder setResponseValue(int value) {
      response_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public com.fleetmgr.interfaces.facade.control.Response getResponse() {
      com.fleetmgr.interfaces.facade.control.Response result = com.fleetmgr.interfaces.facade.control.Response.valueOf(response_);
      return result == null ? com.fleetmgr.interfaces.facade.control.Response.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public Builder setResponse(com.fleetmgr.interfaces.facade.control.Response value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      response_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.Response response = 2;</code>
     */
    public Builder clearResponse() {
      
      response_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.fleetmgr.interfaces.facade.control.SetupResponse attach_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.SetupResponse, com.fleetmgr.interfaces.facade.control.SetupResponse.Builder, com.fleetmgr.interfaces.facade.control.SetupResponseOrBuilder> attachBuilder_;
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public boolean hasAttach() {
      return attachBuilder_ != null || attach_ != null;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public com.fleetmgr.interfaces.facade.control.SetupResponse getAttach() {
      if (attachBuilder_ == null) {
        return attach_ == null ? com.fleetmgr.interfaces.facade.control.SetupResponse.getDefaultInstance() : attach_;
      } else {
        return attachBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public Builder setAttach(com.fleetmgr.interfaces.facade.control.SetupResponse value) {
      if (attachBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attach_ = value;
        onChanged();
      } else {
        attachBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public Builder setAttach(
        com.fleetmgr.interfaces.facade.control.SetupResponse.Builder builderForValue) {
      if (attachBuilder_ == null) {
        attach_ = builderForValue.build();
        onChanged();
      } else {
        attachBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public Builder mergeAttach(com.fleetmgr.interfaces.facade.control.SetupResponse value) {
      if (attachBuilder_ == null) {
        if (attach_ != null) {
          attach_ =
            com.fleetmgr.interfaces.facade.control.SetupResponse.newBuilder(attach_).mergeFrom(value).buildPartial();
        } else {
          attach_ = value;
        }
        onChanged();
      } else {
        attachBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public Builder clearAttach() {
      if (attachBuilder_ == null) {
        attach_ = null;
        onChanged();
      } else {
        attach_ = null;
        attachBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public com.fleetmgr.interfaces.facade.control.SetupResponse.Builder getAttachBuilder() {
      
      onChanged();
      return getAttachFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    public com.fleetmgr.interfaces.facade.control.SetupResponseOrBuilder getAttachOrBuilder() {
      if (attachBuilder_ != null) {
        return attachBuilder_.getMessageOrBuilder();
      } else {
        return attach_ == null ?
            com.fleetmgr.interfaces.facade.control.SetupResponse.getDefaultInstance() : attach_;
      }
    }
    /**
     * <pre>
     * responses, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.facade.control.SetupResponse attach = 50;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.SetupResponse, com.fleetmgr.interfaces.facade.control.SetupResponse.Builder, com.fleetmgr.interfaces.facade.control.SetupResponseOrBuilder> 
        getAttachFieldBuilder() {
      if (attachBuilder_ == null) {
        attachBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.facade.control.SetupResponse, com.fleetmgr.interfaces.facade.control.SetupResponse.Builder, com.fleetmgr.interfaces.facade.control.SetupResponseOrBuilder>(
                getAttach(),
                getParentForChildren(),
                isClean());
        attach_ = null;
      }
      return attachBuilder_;
    }

    private com.fleetmgr.interfaces.AddChannelsResponse requestChannels_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.AddChannelsResponse, com.fleetmgr.interfaces.AddChannelsResponse.Builder, com.fleetmgr.interfaces.AddChannelsResponseOrBuilder> requestChannelsBuilder_;
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public boolean hasRequestChannels() {
      return requestChannelsBuilder_ != null || requestChannels_ != null;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public com.fleetmgr.interfaces.AddChannelsResponse getRequestChannels() {
      if (requestChannelsBuilder_ == null) {
        return requestChannels_ == null ? com.fleetmgr.interfaces.AddChannelsResponse.getDefaultInstance() : requestChannels_;
      } else {
        return requestChannelsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public Builder setRequestChannels(com.fleetmgr.interfaces.AddChannelsResponse value) {
      if (requestChannelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestChannels_ = value;
        onChanged();
      } else {
        requestChannelsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public Builder setRequestChannels(
        com.fleetmgr.interfaces.AddChannelsResponse.Builder builderForValue) {
      if (requestChannelsBuilder_ == null) {
        requestChannels_ = builderForValue.build();
        onChanged();
      } else {
        requestChannelsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public Builder mergeRequestChannels(com.fleetmgr.interfaces.AddChannelsResponse value) {
      if (requestChannelsBuilder_ == null) {
        if (requestChannels_ != null) {
          requestChannels_ =
            com.fleetmgr.interfaces.AddChannelsResponse.newBuilder(requestChannels_).mergeFrom(value).buildPartial();
        } else {
          requestChannels_ = value;
        }
        onChanged();
      } else {
        requestChannelsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public Builder clearRequestChannels() {
      if (requestChannelsBuilder_ == null) {
        requestChannels_ = null;
        onChanged();
      } else {
        requestChannels_ = null;
        requestChannelsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public com.fleetmgr.interfaces.AddChannelsResponse.Builder getRequestChannelsBuilder() {
      
      onChanged();
      return getRequestChannelsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    public com.fleetmgr.interfaces.AddChannelsResponseOrBuilder getRequestChannelsOrBuilder() {
      if (requestChannelsBuilder_ != null) {
        return requestChannelsBuilder_.getMessageOrBuilder();
      } else {
        return requestChannels_ == null ?
            com.fleetmgr.interfaces.AddChannelsResponse.getDefaultInstance() : requestChannels_;
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.AddChannelsResponse requestChannels = 51;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.AddChannelsResponse, com.fleetmgr.interfaces.AddChannelsResponse.Builder, com.fleetmgr.interfaces.AddChannelsResponseOrBuilder> 
        getRequestChannelsFieldBuilder() {
      if (requestChannelsBuilder_ == null) {
        requestChannelsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.AddChannelsResponse, com.fleetmgr.interfaces.AddChannelsResponse.Builder, com.fleetmgr.interfaces.AddChannelsResponseOrBuilder>(
                getRequestChannels(),
                getParentForChildren(),
                isClean());
        requestChannels_ = null;
      }
      return requestChannelsBuilder_;
    }

    private com.fleetmgr.interfaces.HandoverData handoverData_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.HandoverData, com.fleetmgr.interfaces.HandoverData.Builder, com.fleetmgr.interfaces.HandoverDataOrBuilder> handoverDataBuilder_;
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public boolean hasHandoverData() {
      return handoverDataBuilder_ != null || handoverData_ != null;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public com.fleetmgr.interfaces.HandoverData getHandoverData() {
      if (handoverDataBuilder_ == null) {
        return handoverData_ == null ? com.fleetmgr.interfaces.HandoverData.getDefaultInstance() : handoverData_;
      } else {
        return handoverDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public Builder setHandoverData(com.fleetmgr.interfaces.HandoverData value) {
      if (handoverDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        handoverData_ = value;
        onChanged();
      } else {
        handoverDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public Builder setHandoverData(
        com.fleetmgr.interfaces.HandoverData.Builder builderForValue) {
      if (handoverDataBuilder_ == null) {
        handoverData_ = builderForValue.build();
        onChanged();
      } else {
        handoverDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public Builder mergeHandoverData(com.fleetmgr.interfaces.HandoverData value) {
      if (handoverDataBuilder_ == null) {
        if (handoverData_ != null) {
          handoverData_ =
            com.fleetmgr.interfaces.HandoverData.newBuilder(handoverData_).mergeFrom(value).buildPartial();
        } else {
          handoverData_ = value;
        }
        onChanged();
      } else {
        handoverDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public Builder clearHandoverData() {
      if (handoverDataBuilder_ == null) {
        handoverData_ = null;
        onChanged();
      } else {
        handoverData_ = null;
        handoverDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public com.fleetmgr.interfaces.HandoverData.Builder getHandoverDataBuilder() {
      
      onChanged();
      return getHandoverDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    public com.fleetmgr.interfaces.HandoverDataOrBuilder getHandoverDataOrBuilder() {
      if (handoverDataBuilder_ != null) {
        return handoverDataBuilder_.getMessageOrBuilder();
      } else {
        return handoverData_ == null ?
            com.fleetmgr.interfaces.HandoverData.getDefaultInstance() : handoverData_;
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.HandoverData handoverData = 52;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.HandoverData, com.fleetmgr.interfaces.HandoverData.Builder, com.fleetmgr.interfaces.HandoverDataOrBuilder> 
        getHandoverDataFieldBuilder() {
      if (handoverDataBuilder_ == null) {
        handoverDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.HandoverData, com.fleetmgr.interfaces.HandoverData.Builder, com.fleetmgr.interfaces.HandoverDataOrBuilder>(
                getHandoverData(),
                getParentForChildren(),
                isClean());
        handoverData_ = null;
      }
      return handoverDataBuilder_;
    }

    private com.fleetmgr.interfaces.AttachChannelsRequest attachChannels_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.AttachChannelsRequest, com.fleetmgr.interfaces.AttachChannelsRequest.Builder, com.fleetmgr.interfaces.AttachChannelsRequestOrBuilder> attachChannelsBuilder_;
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public boolean hasAttachChannels() {
      return attachChannelsBuilder_ != null || attachChannels_ != null;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public com.fleetmgr.interfaces.AttachChannelsRequest getAttachChannels() {
      if (attachChannelsBuilder_ == null) {
        return attachChannels_ == null ? com.fleetmgr.interfaces.AttachChannelsRequest.getDefaultInstance() : attachChannels_;
      } else {
        return attachChannelsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public Builder setAttachChannels(com.fleetmgr.interfaces.AttachChannelsRequest value) {
      if (attachChannelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attachChannels_ = value;
        onChanged();
      } else {
        attachChannelsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public Builder setAttachChannels(
        com.fleetmgr.interfaces.AttachChannelsRequest.Builder builderForValue) {
      if (attachChannelsBuilder_ == null) {
        attachChannels_ = builderForValue.build();
        onChanged();
      } else {
        attachChannelsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public Builder mergeAttachChannels(com.fleetmgr.interfaces.AttachChannelsRequest value) {
      if (attachChannelsBuilder_ == null) {
        if (attachChannels_ != null) {
          attachChannels_ =
            com.fleetmgr.interfaces.AttachChannelsRequest.newBuilder(attachChannels_).mergeFrom(value).buildPartial();
        } else {
          attachChannels_ = value;
        }
        onChanged();
      } else {
        attachChannelsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public Builder clearAttachChannels() {
      if (attachChannelsBuilder_ == null) {
        attachChannels_ = null;
        onChanged();
      } else {
        attachChannels_ = null;
        attachChannelsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public com.fleetmgr.interfaces.AttachChannelsRequest.Builder getAttachChannelsBuilder() {
      
      onChanged();
      return getAttachChannelsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    public com.fleetmgr.interfaces.AttachChannelsRequestOrBuilder getAttachChannelsOrBuilder() {
      if (attachChannelsBuilder_ != null) {
        return attachChannelsBuilder_.getMessageOrBuilder();
      } else {
        return attachChannels_ == null ?
            com.fleetmgr.interfaces.AttachChannelsRequest.getDefaultInstance() : attachChannels_;
      }
    }
    /**
     * <pre>
     * requests, defined by Command/Response fields
     * </pre>
     *
     * <code>.com.fleetmgr.interfaces.AttachChannelsRequest attachChannels = 100;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.AttachChannelsRequest, com.fleetmgr.interfaces.AttachChannelsRequest.Builder, com.fleetmgr.interfaces.AttachChannelsRequestOrBuilder> 
        getAttachChannelsFieldBuilder() {
      if (attachChannelsBuilder_ == null) {
        attachChannelsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.AttachChannelsRequest, com.fleetmgr.interfaces.AttachChannelsRequest.Builder, com.fleetmgr.interfaces.AttachChannelsRequestOrBuilder>(
                getAttachChannels(),
                getParentForChildren(),
                isClean());
        attachChannels_ = null;
      }
      return attachChannelsBuilder_;
    }

    private com.fleetmgr.interfaces.ChannelsResponse channels_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.ChannelsResponse, com.fleetmgr.interfaces.ChannelsResponse.Builder, com.fleetmgr.interfaces.ChannelsResponseOrBuilder> channelsBuilder_;
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public boolean hasChannels() {
      return channelsBuilder_ != null || channels_ != null;
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public com.fleetmgr.interfaces.ChannelsResponse getChannels() {
      if (channelsBuilder_ == null) {
        return channels_ == null ? com.fleetmgr.interfaces.ChannelsResponse.getDefaultInstance() : channels_;
      } else {
        return channelsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public Builder setChannels(com.fleetmgr.interfaces.ChannelsResponse value) {
      if (channelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        channels_ = value;
        onChanged();
      } else {
        channelsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public Builder setChannels(
        com.fleetmgr.interfaces.ChannelsResponse.Builder builderForValue) {
      if (channelsBuilder_ == null) {
        channels_ = builderForValue.build();
        onChanged();
      } else {
        channelsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public Builder mergeChannels(com.fleetmgr.interfaces.ChannelsResponse value) {
      if (channelsBuilder_ == null) {
        if (channels_ != null) {
          channels_ =
            com.fleetmgr.interfaces.ChannelsResponse.newBuilder(channels_).mergeFrom(value).buildPartial();
        } else {
          channels_ = value;
        }
        onChanged();
      } else {
        channelsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public Builder clearChannels() {
      if (channelsBuilder_ == null) {
        channels_ = null;
        onChanged();
      } else {
        channels_ = null;
        channelsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public com.fleetmgr.interfaces.ChannelsResponse.Builder getChannelsBuilder() {
      
      onChanged();
      return getChannelsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    public com.fleetmgr.interfaces.ChannelsResponseOrBuilder getChannelsOrBuilder() {
      if (channelsBuilder_ != null) {
        return channelsBuilder_.getMessageOrBuilder();
      } else {
        return channels_ == null ?
            com.fleetmgr.interfaces.ChannelsResponse.getDefaultInstance() : channels_;
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.ChannelsResponse channels = 101;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.ChannelsResponse, com.fleetmgr.interfaces.ChannelsResponse.Builder, com.fleetmgr.interfaces.ChannelsResponseOrBuilder> 
        getChannelsFieldBuilder() {
      if (channelsBuilder_ == null) {
        channelsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.ChannelsResponse, com.fleetmgr.interfaces.ChannelsResponse.Builder, com.fleetmgr.interfaces.ChannelsResponseOrBuilder>(
                getChannels(),
                getParentForChildren(),
                isClean());
        channels_ = null;
      }
      return channelsBuilder_;
    }

    private com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.HeartbeatRequest, com.fleetmgr.interfaces.facade.control.HeartbeatRequest.Builder, com.fleetmgr.interfaces.facade.control.HeartbeatRequestOrBuilder> heartbeatBuilder_;
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public boolean hasHeartbeat() {
      return heartbeatBuilder_ != null || heartbeat_ != null;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public com.fleetmgr.interfaces.facade.control.HeartbeatRequest getHeartbeat() {
      if (heartbeatBuilder_ == null) {
        return heartbeat_ == null ? com.fleetmgr.interfaces.facade.control.HeartbeatRequest.getDefaultInstance() : heartbeat_;
      } else {
        return heartbeatBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public Builder setHeartbeat(com.fleetmgr.interfaces.facade.control.HeartbeatRequest value) {
      if (heartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        heartbeat_ = value;
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public Builder setHeartbeat(
        com.fleetmgr.interfaces.facade.control.HeartbeatRequest.Builder builderForValue) {
      if (heartbeatBuilder_ == null) {
        heartbeat_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public Builder mergeHeartbeat(com.fleetmgr.interfaces.facade.control.HeartbeatRequest value) {
      if (heartbeatBuilder_ == null) {
        if (heartbeat_ != null) {
          heartbeat_ =
            com.fleetmgr.interfaces.facade.control.HeartbeatRequest.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
        } else {
          heartbeat_ = value;
        }
        onChanged();
      } else {
        heartbeatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public Builder clearHeartbeat() {
      if (heartbeatBuilder_ == null) {
        heartbeat_ = null;
        onChanged();
      } else {
        heartbeat_ = null;
        heartbeatBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public com.fleetmgr.interfaces.facade.control.HeartbeatRequest.Builder getHeartbeatBuilder() {
      
      onChanged();
      return getHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    public com.fleetmgr.interfaces.facade.control.HeartbeatRequestOrBuilder getHeartbeatOrBuilder() {
      if (heartbeatBuilder_ != null) {
        return heartbeatBuilder_.getMessageOrBuilder();
      } else {
        return heartbeat_ == null ?
            com.fleetmgr.interfaces.facade.control.HeartbeatRequest.getDefaultInstance() : heartbeat_;
      }
    }
    /**
     * <code>.com.fleetmgr.interfaces.facade.control.HeartbeatRequest heartbeat = 102;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fleetmgr.interfaces.facade.control.HeartbeatRequest, com.fleetmgr.interfaces.facade.control.HeartbeatRequest.Builder, com.fleetmgr.interfaces.facade.control.HeartbeatRequestOrBuilder> 
        getHeartbeatFieldBuilder() {
      if (heartbeatBuilder_ == null) {
        heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fleetmgr.interfaces.facade.control.HeartbeatRequest, com.fleetmgr.interfaces.facade.control.HeartbeatRequest.Builder, com.fleetmgr.interfaces.facade.control.HeartbeatRequestOrBuilder>(
                getHeartbeat(),
                getParentForChildren(),
                isClean());
        heartbeat_ = null;
      }
      return heartbeatBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.fleetmgr.interfaces.facade.control.ControlMessage)
  }

  // @@protoc_insertion_point(class_scope:com.fleetmgr.interfaces.facade.control.ControlMessage)
  private static final com.fleetmgr.interfaces.facade.control.ControlMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fleetmgr.interfaces.facade.control.ControlMessage();
  }

  public static com.fleetmgr.interfaces.facade.control.ControlMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ControlMessage>
      PARSER = new com.google.protobuf.AbstractParser<ControlMessage>() {
    public ControlMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ControlMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ControlMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ControlMessage> getParserForType() {
    return PARSER;
  }

  public com.fleetmgr.interfaces.facade.control.ControlMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

