// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/facade_service.proto

package com.fleetmgr.interfaces.facade.control;

public final class FacadeServiceOuterClass {
  private FacadeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#facade/control/facade_service.proto\022&c" +
      "om.fleetmgr.interfaces.facade.control\032\031c" +
      "ommon/add_channels.proto\032\034common/attach_" +
      "channels.proto\032\032common/handover_data.pro" +
      "to\032\032facade/control/setup.proto\032\036facade/c" +
      "ontrol/heartbeat.proto\"\200\004\n\rClientMessage" +
      "\022@\n\007command\030\001 \001(\0162/.com.fleetmgr.interfa" +
      "ces.facade.control.Command\022B\n\010response\030\002" +
      " \001(\01620.com.fleetmgr.interfaces.facade.co" +
      "ntrol.Response\022\017\n\007message\030\003 \001(\t\022D\n\006attac" +
      "h\0302 \001(\01324.com.fleetmgr.interfaces.facade" +
      ".control.SetupRequest\022D\n\017requestChannels" +
      "\0303 \001(\0132+.com.fleetmgr.interfaces.AddChan" +
      "nelsRequest\022A\n\016attachChannels\030d \001(\0132).co" +
      "m.fleetmgr.interfaces.ChannelsResponse\022;" +
      "\n\014handoverData\030e \001(\0132%.com.fleetmgr.inte" +
      "rfaces.HandoverData\022L\n\theartbeat\030f \001(\01329" +
      ".com.fleetmgr.interfaces.facade.control." +
      "HeartbeatResponse\"\304\004\n\016ControlMessage\022@\n\007" +
      "command\030\001 \001(\0162/.com.fleetmgr.interfaces." +
      "facade.control.Command\022B\n\010response\030\002 \001(\016" +
      "20.com.fleetmgr.interfaces.facade.contro" +
      "l.Response\022\017\n\007message\030\003 \001(\t\022E\n\006attach\0302 " +
      "\001(\01325.com.fleetmgr.interfaces.facade.con" +
      "trol.SetupResponse\022E\n\017requestChannels\0303 " +
      "\001(\0132,.com.fleetmgr.interfaces.AddChannel" +
      "sResponse\022;\n\014handoverData\0304 \001(\0132%.com.fl" +
      "eetmgr.interfaces.HandoverData\022F\n\016attach" +
      "Channels\030d \001(\0132..com.fleetmgr.interfaces" +
      ".AttachChannelsRequest\022;\n\010channels\030e \001(\013" +
      "2).com.fleetmgr.interfaces.ChannelsRespo" +
      "nse\022K\n\theartbeat\030f \001(\01328.com.fleetmgr.in" +
      "terfaces.facade.control.HeartbeatRequest" +
      "*\345\002\n\007Command\022\021\n\rUNDEFINED_CMD\020\000\022\r\n\tHEART" +
      "BEAT\020\001\022\t\n\005SETUP\020\002\022\013\n\007RELEASE\020\003\022\020\n\014ADD_CH" +
      "ANNELS\020\013\022\023\n\017REMOVE_CHANNELS\020\014\022\023\n\017ATTACH_" +
      "CHANNELS\020\r\022\024\n\020RELEASE_CHANNELS\020\016\022\022\n\016CHAN" +
      "NELS_READY\020\017\022\023\n\017REQUEST_CONTROL\020\025\022\023\n\017REL" +
      "EASE_CONTROL\020\026\022\024\n\020CONTROL_RELEASED\020\027\022\021\n\r" +
      "CONTROL_READY\020\030\022\023\n\017OPERATION_ENDED\020\037\022\026\n\022" +
      "DEVICE_UNREACHABLE\020)\022\026\n\022LEADER_UNREACHAB" +
      "LE\020*\022\014\n\010RECOVERY\020+\022\024\n\020DEVICE_RECOVERED\020," +
      "*9\n\010Response\022\021\n\rUNDEFINED_RSP\020\000\022\014\n\010ACCEP" +
      "TED\020\001\022\014\n\010REJECTED\020\0022\215\001\n\rFacadeService\022|\n" +
      "\007control\0225.com.fleetmgr.interfaces.facad" +
      "e.control.ClientMessage\0326.com.fleetmgr.i" +
      "nterfaces.facade.control.ControlMessage(" +
      "\0010\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fleetmgr.interfaces.AddChannels.getDescriptor(),
          com.fleetmgr.interfaces.AttachChannels.getDescriptor(),
          com.fleetmgr.interfaces.HandoverDataOuterClass.getDescriptor(),
          com.fleetmgr.interfaces.facade.control.Setup.getDescriptor(),
          com.fleetmgr.interfaces.facade.control.Heartbeat.getDescriptor(),
        }, assigner);
    internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_facade_control_ClientMessage_descriptor,
        new java.lang.String[] { "Command", "Response", "Message", "Attach", "RequestChannels", "AttachChannels", "HandoverData", "Heartbeat", });
    internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fleetmgr_interfaces_facade_control_ControlMessage_descriptor,
        new java.lang.String[] { "Command", "Response", "Message", "Attach", "RequestChannels", "HandoverData", "AttachChannels", "Channels", "Heartbeat", });
    com.fleetmgr.interfaces.AddChannels.getDescriptor();
    com.fleetmgr.interfaces.AttachChannels.getDescriptor();
    com.fleetmgr.interfaces.HandoverDataOuterClass.getDescriptor();
    com.fleetmgr.interfaces.facade.control.Setup.getDescriptor();
    com.fleetmgr.interfaces.facade.control.Heartbeat.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
