// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/heartbeat.proto

package com.fleetmgr.interfaces.facade.control;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.facade.control.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 key = 1;</code>
   */
  long getKey();

  /**
   * <code>.com.fleetmgr.interfaces.Location location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.com.fleetmgr.interfaces.Location location = 2;</code>
   */
  com.fleetmgr.interfaces.Location getLocation();
  /**
   * <code>.com.fleetmgr.interfaces.Location location = 2;</code>
   */
  com.fleetmgr.interfaces.LocationOrBuilder getLocationOrBuilder();
}
