// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/heartbeat.proto

package com.fleetmgr.interfaces.facade.control;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.facade.control.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 key = 1;</code>
   */
  long getKey();
}
