// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/facade_service.proto

package com.fleetmgr.interfaces.facade.control;

/**
 * Protobuf enum {@code com.fleetmgr.interfaces.facade.control.Response}
 */
public enum Response
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNDEFINED_RSP = 0;</code>
   */
  UNDEFINED_RSP(0),
  /**
   * <code>ACCEPTED = 1;</code>
   */
  ACCEPTED(1),
  /**
   * <code>REJECTED = 2;</code>
   */
  REJECTED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNDEFINED_RSP = 0;</code>
   */
  public static final int UNDEFINED_RSP_VALUE = 0;
  /**
   * <code>ACCEPTED = 1;</code>
   */
  public static final int ACCEPTED_VALUE = 1;
  /**
   * <code>REJECTED = 2;</code>
   */
  public static final int REJECTED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Response valueOf(int value) {
    return forNumber(value);
  }

  public static Response forNumber(int value) {
    switch (value) {
      case 0: return UNDEFINED_RSP;
      case 1: return ACCEPTED;
      case 2: return REJECTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Response>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Response> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Response>() {
          public Response findValueByNumber(int number) {
            return Response.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.fleetmgr.interfaces.facade.control.FacadeServiceOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final Response[] VALUES = values();

  public static Response valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Response(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.fleetmgr.interfaces.facade.control.Response)
}

