// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/setup.proto

package com.fleetmgr.interfaces.facade.control;

public interface SetupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.facade.control.SetupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
