// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade/control/setup.proto

package com.fleetmgr.interfaces.facade.control;

public interface SetupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fleetmgr.interfaces.facade.control.SetupResponse)
    com.google.protobuf.MessageOrBuilder {
}
